### ISSUE TITLE
Multiple YAML files

### ISSUE THREAD

**Issue by jhagege** [omni-us/jsonargparse#1]
Looks great :) 
Would it be possible to load from multiple YAML files ?
One YAML would be including the defaults, and the other ones only the diffs, in a cascading manner (according to order of loading).
Thanks.

**Comment by mauvilsa** [comment]
Yes, that is possible. Look at https://omni-us.github.io/yamlargparse/#yamlargparse.ArgumentParser.__init__ . Basically when you would create the parser object for example as follows:

```
parser = yamlargparse.ArgumentParser(
    default_config_files=['/etc/myapp/*.yaml', '~/.config/myapp/*.yaml']
    prog='app',
    description='Description for my app.')
```

And then there can also be a config file provided as a command line argument by adding `parser.add_argument('--cfg', action=yamlargparse.ActionConfigFile)`.
