### ISSUE TITLE
[Feature Request] YAML(json) variables

### ISSUE THREAD

**Issue by Liangtaiwan** [omni-us/jsonargparse#10]
In ansible, variables can be defined in yaml file.
I think it is very useful. Maybe you can consider it as a feature.

Here are examples.
https://docs.ansible.com/ansible/latest/reference_appendices/YAMLSyntax.html

Further, Ansible uses "{{ var }}" for variables. If a value after a colon starts with a "{", YAML will think it is a dictionary, so you must quote it, like so:

```
foo: "{{ variable }}"
```
If your value starts with a quote the entire value must be quoted, not just part of it. Here are some additional examples of how to properly quote things:

```
foo: "{{ variable }}/additional/string/literal"
foo2: "{{ variable }}\\backslashes\\are\\also\\special\\characters"
foo3: "even if it's just a string literal it must all be quoted"
```

Moreover, you can include variables from other files
https://docs.ansible.com/ansible/latest/modules/include_vars_module.html

**Comment by mauvilsa** [comment]
@Liangtaiwan thank you for the suggestion. I have had a quick look at ansible and from what I see that that handling of variables in yaml files is a core part of ansible not implemented as an independent python package. Even though the documentation clearly explains the parsing of variables, it not a good idea to reinvent the wheel implementing the same behavior again in jsonargparse. If it were an independent python package I could consider adding the support here. If you really would like this, start by creating an issue in ansible to ask if it would be possible to make this an independent package and if they would consider doing it.

As a side note, bare in mind that jsonargparse already supports jsonnet which provides variables and more. It is not yaml, but still probably is good enough for any use case you might be considering.
