### ISSUE TITLE
Support the Enum behaviour with `Literal`

### ISSUE THREAD

**Issue by carmocca** [omni-us/jsonargparse#106]
It would be nice if `jsonargparse` supported choices with `typing.Literal`.

So this script:

```python
from typing import Union

import jsonargparse
from typing_extensions import Literal


def fn(choice: Union[Literal["A"], Literal["B"]]):
    if choice == "A":
        ...
    elif choice == "B":
        ...

parser = jsonargparse.ArgumentParser()
parser.add_function_arguments(fn)
parser.print_help()
```

```console
<function fn at 0x10be09550>:
  --choice CHOICE  (required, type: Union[Literal['A'], Literal['B']])
```

would be equal to

```python
from enum import Enum

import jsonargparse


class Choice(str, Enum):
    A = "A"
    B = "B"


def fn(choice: Choice):
    if choice == "A":
        ...
    elif choice == "B":
        ...

parser = jsonargparse.ArgumentParser()
parser.add_function_arguments(fn)
parser.print_help()
```

```console
<function fn at 0x109aab550>:
  --choice {A,B}  (required, type: Choice)
```

with the better help message and input validation

**Comment by mauvilsa** [comment]
From what I see the validation of `Literal` works as expected, so I am a bit confused with "the better ... and input validation". This seems to be just a request to change the help message. And the only difference would be that instead of `CHOICE` it would be `{A,B}`. Correct?

**Comment by carmocca** [comment]
Yes 😄

**Comment by mauvilsa** [comment]
This is now done. However, note that it has been done for a type hint like `Literal["A", "B"]`. Having a union of individual literals shouldn't be used and makes no sense to have special support for.
