### ISSUE TITLE
Better `argparse.REMAINDER` support

### ISSUE THREAD

**Issue by carmocca** [omni-us/jsonargparse#107]
Hi!

I'm trying to implement a parser that takes arbitrary extra arguments which will be passed to another parser. I found that `argparse` has `REMAINDER` exactly for this purpose: 

```console
$ python script.py --an_argument 123 --other_argument 321 foo bar baz
                                     <----------REMAINDER----------->
```

```python
import argparse

import jsonargparse

parser = jsonargparse.ArgumentParser()
parser.add_argument("--an_argument")
parser.add_argument("--downstream_args", nargs=argparse.REMAINDER)

args = parser.parse_args(["--an_argument", "123", "--other_argument", "321", "foo", "bar", "baz"])
# script.py: error: Unrecognized arguments: --other_argument 321 foo bar baz
```

However, it's not really working well because it fails if an optional argument is passed first (as shown above). There's an old discussion about this in https://bugs.python.org/issue17050 where the suggestion is to add a gatekeep (`--`) and to use `*` instead.

```console
$ python script.py --an_argument 123 -- --other_argument 321 foo bar baz
                                     ^^ <----------REMAINDER----------->
```

```python
...
parser.add_argument("downstream_args", nargs=argparse.ZERO_OR_MORE)

args = parser.parse_args(["--an_argument", "123", "--", "--other_argument", "321", "foo", "bar", "baz"])
print(args)  # Namespace(an_argument='123', downstream_args=['--other_argument', '321', 'foo', 'bar', 'baz'])
```

Note that it would work without `--` if the first argument was positional

```python
...
parser.add_argument("downstream_args", nargs=argparse.REMAINDER)

args = parser.parse_args(["--an_argument", "123", "foo", "--other_argument", "321", "bar", "baz"])
print(args)  # Namespace(an_argument='123', downstream_args=['foo', '--other_argument', '321', 'bar', 'baz'])
```

Do you think `jsonargparse` could fix this? Or provide an alternative for this use-case? Is there one already?

I want to avoid using `--` as a separator as it's not intuitive for new users.

### Context

I'm working on the `FlashCLI`, where I want to have a root parser that takes a subcommand and remainder args which then get passed to the downstream task CLI

```console
$ flash image_classification --trainer.max_epochs 123
<------ROOT PARSER-------> <------REMAINDER------->
```

So the root parser has an `image_classification` subcommand parser with `downstream_args` optional `REMAINDER` argument as shown above.

https://github.com/karthikrangasai/lightning-flash/blob/be6615336ad35b7c29b67643f21d2e770011521d/flash/__main__.py#L49-L58

**Comment by mauvilsa** [comment]
> Do you think jsonargparse could fix this?

A fix for this would likely be an ugly hack since that is simply the way argparse works.

> Or provide an alternative for this use-case? Is there one already?

For the use case of the context I do think there is an alternative already. From what I understand it is just

```python
from jsonargparse import ArgumentParser, REMAINDER

subparser = ArgumentParser()
subparser.add_argument('args', nargs=REMAINDER)

parser = ArgumentParser()
subcommands = parser.add_subcommands()
subcommands.add_subcommand('image_classification', subparser)

cfg = parser.parse_args()
# Use cfg.subcommand to choose downstream task
# Use cfg[cfg.subcommand].args for the downstream task args
```

Though from what I see you were almost doing this already. The main difference being the `add_function_arguments` to the subcommand. I didn't understand the need for this but can't this be part of what is done after the first `parse_args`?

**Comment by mauvilsa** [comment]
@carmocca any comment based on what I wrote?
