### ISSUE TITLE
Is it possible to drop init_args?

### ISSUE THREAD

**Issue by florianblume** [omni-us/jsonargparse#113]
I've tried to find out in the code whether there are technical reasons for why we need `init_args` in configs to pass the init arguments for subclasses. I assume there is but I can't see it and was also wondering whether there's a way around it.

My issue is somewhat related to #89.

I'm using Pytorch Lightning and would like to pass the init arguments to my `LightningModule` subclasses in the same way I pass them to the trainer:

    trainer:
        gpus: 2
        deterministic: true
        ...

since this way I can omit `init_args` in the command line (which makes commands pretty long) and I can pass overwrite parameters in additional configs without having to specify the `class_path` again (it complains when I only pass `init_args`). This drove me to putting more and more stuff into the config file I edit before running experiments, instead of having most of it in the default config file.

I assume that you don't need the `init_args` part when you don't pass subclasses (as in the case of the trainer class) but is there a way to achieve this for subclasses, too, that I'm missing? I guess I could fake it by inserting `init_args` into the config before class instantiation but that feels a bit wrong. Could it be implemented properly? I'd also be happy to help.

**Comment by mauvilsa** [comment]
Yes, it is possible and certainly related to #89. The initial concept was simple, a subclass is a single argument (one action class instance for argparse) which requires to have both `class_path` and `init_args`. Extending this as suggested here and in #89 is considerably more complex. The limitation is only that this needs to be properly thought through, designed, consider how this interacts with all other features, implemented, tested, etc. Essentially it is not a small task.

Help is certainly welcome. I will try to create a list of things that I think need to be done to get this going, hopefully with you and more people contributing.

**Comment by florianblume** [comment]
Ok cool, keep me posted when you've got a list of what to do and we can see where I can jump in!

**Comment by mauvilsa** [comment]
In https://github.com/omni-us/jsonargparse/issues/89#issuecomment-1135890325 it was suggested to keep `init_args` but not have `class_path`. Some relevant explanation about constraints is this other https://github.com/omni-us/jsonargparse/issues/89#issuecomment-1138184483.

**Comment by florianblume** [comment]
Yes, thanks for the extensive comment! As soon as there are tasks to do I'd be happy to help implement them.

**Comment by mauvilsa** [comment]
With commit https://github.com/omni-us/jsonargparse/commit/44eb5df729892e270612ef19773e2a25604c6b3e it is now possible to give `init_args` in a config without specifying the `class_path`. It is possible to give nested in an `init_args` or directly without nesting in `init_args`. See the unit test for an example https://github.com/omni-us/jsonargparse/blob/44eb5df729892e270612ef19773e2a25604c6b3e/jsonargparse_tests/test_typehints.py#L625-L643.

**Comment by florianblume** [comment]
Love it!
