### ISSUE TITLE
Namespace TypeError with non-str inputs

### ISSUE THREAD

**Issue by carmocca** [omni-us/jsonargparse#116]
```python
from jsonargparse import Namespace
x = Namespace({"foo": "bar"})
print(x.get(None, "baz"))
```

```python
TypeError: argument of type 'NoneType' is not iterable
```

Using different types with `get` should be allowed even if `Namespace` only accepts string dictionary keys

**Comment by mauvilsa** [comment]
Fixed in https://github.com/omni-us/jsonargparse/commit/4403d9ec8cc1ee2d1c331367cabe9bc259b55bf8.
