### ISSUE TITLE
[Feature Request] Automatically add config-file entries to parser

### ISSUE THREAD

**Issue by justusschock** [omni-us/jsonargparse#118]
Hey, thanks for this amazing framework!

I used to use `hydra` and want to switch to `jsonargparse`/`LightningCLI`. 
The thing that currently blocks me (or maybe I just haven't found how to do it properly):

In `hydra`, if you provide a config-file, it is not necessary to add every single argument to a parser. It reads the yaml and has the arguments in it's config.
In `jsonargparse` this does not seem to be possible. So you would have to add every single argument of that config-file to the parser was well which to me seems to be some kind of duplicated effort.

I understand that this makes sense from a CLI perspective, where you need help strings etc. but for config-files I would really like the arguments to be registered "automatically" even though there may not be any help strings and only the most basic python types supported.

Do you think this would be reasonable to implement? If not - do you have an idea, how I could implement this on my own/how much effort this would be? My current solution is to manually load the yaml file once beforehand and there register everything before relying on the `jsonargparse` parsing, but that seems to be kind of non-ideal to me.

**Comment by mauvilsa** [comment]
I think I need a bit more explanation to understand what you mean. Is this for all entries of the config file? How and where are these unregistered arguments used? I have seen the documentation of `hydra` and a couple of tutorials, but have never actually used it. Might be the reason why I don't fully understand. Maybe a simple example could help.

**Comment by justusschock** [comment]
If you have an example config file like 

``` yaml
db:
  driver: mysql
  user: omry
  pass: secret
```

with the following snippet:
```python
import hydra
from omegaconf import DictConfig, OmegaConf

@hydra.main(config_path="conf", config_name="config")
def my_app(cfg : DictConfig) -> None:
    print(OmegaConf.to_yaml(cfg))

if __name__ == "__main__":
    my_app()
```

you'd get something like 
```
$ python my_app.py
db:
  driver: mysql
  pass: secret
  user: omry
```

without manually registering each argument to the parser, like you'd have to in `jsonargparse` currently

Basically this is the behaviour I want to achieve: My config should automatically have everything that is in the file without the need of adding the args to the parser manually, because this would be kind of duplicated

**Comment by mauvilsa** [comment]
An similar code snippet with jsonargparse would be:

```python
import yaml
from typing import Any, Dict
from jsonargparse import CLI

def my_app(cfg: Dict[str, Any]) -> None:
    print(yaml.safe_dump(cfg))

if __name__ == "__main__":
    CLI(my_app)
```

Though I am still not sure if I know yet exactly what you are interested in, if it is just this or something more. Having a single `cfg` parameter that has all the configuration of an app without any validation, kind of looses a the main advantages of using a jsonargparse parser. If the idea is to have a mixture of parameters, ones that have types and others that don't, then it would make a bit more sense for me. Like with `LightningCLI` having a module which has among its parameters one with `Dict[str, Any]` type which would be a dict without any requirements of its content.

**Comment by justusschock** [comment]
the question is more about the loading: When loading from a config file, with `jsonargparse` you have to specify every argument in the parser, right? Is there a way to get rid of this and to just "load everything in that file"?

**Comment by mauvilsa** [comment]
`jsonargparse` is just an extension of `argparse`. You have a parser and you add arguments to it. And if the argument has a type, then when parsing the value is validated. So yes, there must be an argument. But as you see in the code above, there is only one argument `cfg`. And it works almost as what you had with `hydra`. The difference is that the values would be nested inside `cfg`. So if you have a yaml:

```yaml
cfg:
  db:
    driver: mysql
    user: omry
    pass: secret
```

When you run the script the result is analogous:

```bash
$ python my_app.py --config config.yaml
db:
  driver: mysql
  pass: secret
  user: omry
```

It is not necessary for `db`, `driver`, `pass` and `user` to be arguments of the parser.

I am still not sure what you are trying to achieve. If you load a yaml, why add all the yaml keys as arguments to the parser with the types as in the yaml? What would be the use of this parser if you already have the yaml loaded and types would be the same as the ones in the parser? The parser would just convert nested dicts into nested Namespaces.

**Comment by justusschock** [comment]
> The parser would just convert nested dicts into nested Namespaces.
That's true, but it would be more convenient to have it all in one framework and especially well-tested.

>What would be the use of this parser if you already have the yaml loaded and types would be the same as the ones in the parser?
The idea is to not have to load it manually.


Anyways, it seems that this is off-scope for this framework. Thanks a lot for discussing this!

**Comment by florianblume** [comment]
Maybe it's unnecessary that I jump in but I'm still intrigued. When you have something in a config then you surely want to use it somewhere in your code right? In this case you can simply tell jsonargparse to add the function/class/method parameters and arguments as arguments to the parser. So no manual work involved.

Is that what you're looking for?

Or do you have one large config file where a lot of stuff is in which you don't always need (maybe because you execute parts of your scripts only) which you need parsed? I mean the main advantage(at least from my perspective) of jsonargparse is that it implicitly documents what a config file has to look like and keeps config files and code in sync.

**Comment by justusschock** [comment]
@florianblume It's more the later part. So I have huge configs and don't always need everything. Also what I need is often determined by runtime conditions.

**Comment by florianblume** [comment]
I see. I'm not sure whether this is applicable to your case but what I'm doing is splitting the configs into multiple small chunks. I have one for my model, one for my data, etc. And I also have a defaults config file. Depending on which experiment I want to launch, I choose the respective config files.

I'm calling my code like `python train.py --model configs/model.yaml --data configs/data.yaml --config configs/to_edit.yaml` and then sometimes parameters I change on the fly. But usually I use `to_edit.yaml` to edit parts that are often changing (I'm using pytorch lightning cli which stores the whole final config file so I always know what the full package looked like in the end).

What do you mean by your last sentence? That during runtime certain parts of your code are loaded lazily?

**Comment by justusschock** [comment]
Thanks, I'll see if this is applicable in my case.

By the last sentence, I mean that I have huge code blocks that are not always executed and in fact not even always imported.

**Comment by mauvilsa** [comment]
There is one more tip worth mentioning, that could also not be your case but be useful for people that end up reading this. One of the benefits of having something like `LightningCLI` is that with very few lines of code a `CLI` can be implemented. It might be preferable to implement several simpler more focused `CLIs`  than having a single much more complex one.
