### ISSUE TITLE
[Feature Request] Support print json config when parser mode is jsonnet.

### ISSUE THREAD

**Issue by tshu-w** [omni-us/jsonargparse#123]

**Comment by mauvilsa** [comment]
Not sure if some time ago it did correctly print as json, and maybe broke when the registering of loaders/dumpers were introduced.

**Comment by mauvilsa** [comment]
This is fixed in commit https://github.com/omni-us/jsonargparse/commit/f08329c49b267b9c21a845d533356ec8178c84ec.

**Comment by mauvilsa** [comment]
This is now part of v4.3.0 which has just been released.
