### ISSUE TITLE
Empty stderr output with 4.3.0

### ISSUE THREAD

**Issue by nimashoghi** [omni-us/jsonargparse#128]
It seems like after [the following commit](https://github.com/omni-us/jsonargparse/commit/97e45675926fb192ebad1c513e0334310e160899), I don't get any stderr outputs when the parser errors out.
For example, if you don't provide a required parameter, the process exits with exit code 2, but you don't see anything in the console.
Am I doing something wrong on my end?

**Comment by tshu-w** [comment]
Yes, same issue here. https://github.com/omni-us/jsonargparse/issues/125#issuecomment-1050498871

**Comment by mauvilsa** [comment]
This has been fixed in commit https://github.com/omni-us/jsonargparse/commit/bfeebb78f7cbd4434cb5231f12c7c36c4c5d5766 and it is included in v4.3.1 that has just been released.
