### ISSUE TITLE
Can a sdist be provided on PyPi?

### ISSUE THREAD

**Issue by feynmanliang** [omni-us/jsonargparse#13]
We would like to use this for a project at Facebook, but corporate policies require an sdist be made available. Would it be possible to publish an sdist to PyPi please?

**Comment by mauvilsa** [comment]
Sure, no problem. I have manually added the sdist of the current version and I have modified the circleci config so that the sdist is added every time I release.

**Comment by feynmanliang** [comment]
CC @nimar

Amazing, thank you very much!
