### ISSUE TITLE
Dictionary via cmdline

### ISSUE THREAD

**Issue by justusschock** [omni-us/jsonargparse#130]
Hi,

Is it supported, to have arguments as a dict via cmd?

Suppose I have the following snippted:

```python
import jsonargparse
from typing import Dict
def foo(bar: Dict[str, int]):
    print(bar)

CLI(foo)
```

How would I specify `bar` in this use-case from the terminal? The [docs](https://jsonargparse.readthedocs.io/en/stable/index.html?highlight=Dict#type-hints) state:

> Dict, Mapping, and MutableMapping are supported but only with str or int keys.

but I haven't found any clarification on whether this is only supported via config-file or how to do it from the cmdline.

Any hints would be highly appreciated :)

**Comment by mauvilsa** [comment]
> Is it supported, to have arguments as a dict via cmd?

Yes, it is supported. All values given through command line are parsed using the same function that parses config files. The default loader is pyyaml, so you can use whatever pyyaml supports, i.e., yaml or json syntax. Thus, you can do:

```
cli.py '{"key": 1}'
```
