### ISSUE TITLE
Passing nested config files args as class arguments gives __path__ TypeError

### ISSUE THREAD

**Issue by nathancornille** [omni-us/jsonargparse#134]
Hi,

Consider the following code to reproduce what I mean:
```python
import jsonargparse


class MyClass:

    def __init__(self, arg1: int, arg2: int):
        self.arg1 = arg1
        self.arg2 = arg2


parser = jsonargparse.ArgumentParser()
parser.add_argument('--config',action=jsonargparse.ActionConfigFile)
parser.add_class_arguments(MyClass, 'myclass', as_group=True)
args = parser.parse_args()
print("args:", args)
try:
    mycl = MyClass(**args.myclass)
except TypeError as e:
    print("Error: ", e)
mycl = MyClass(**{k: v for (k, v) in args.myclass.items() if k != '__path__'})
print(mycl.arg1, mycl.arg2)
```
And I have the following yaml files:
```yaml
# file top_config.yaml
myclass: nested_config.yaml
```
```yaml
# file nested_config.yaml
arg1: 1
arg2: 2
```

This gives the following output:
```
args: Namespace(config=[Path_fr(top_cfg.yaml, cwd=/cw/liir_code/NoCsBack/nathan/p2/Video-VQVAE-main)], myclass=Namespace(arg1=1, arg2=2, __path__=Path_fr(nested_config.yaml, cwd=/cw/liir_code/NoCsBack/nathan/p2/Video-VQVAE-main)))
Error:  MyClass.__init__() got an unexpected keyword argument '__path__'
1 2
```
In other words: the \_\_path__ key gets added (I guess for internal reasons), but this messes up initializing a class with **args.myclass, which is what I understood to be the 'default'/'intended' way of doing it.
I can fix it easily by explicitly filtering out the \_\_path__ key, but that doesn't seem like the 'right' way to do it.
So my question is basically: what's the right way to do what I want here? Or how do I avoid having this __path__ variable showing up?

Thanks!

**Comment by mauvilsa** [comment]
There are several intended ways to do this. In most use cases people should use the [instantiate_classes](https://jsonargparse.readthedocs.io/en/stable/#jsonargparse.ArgumentParser.instantiate_classes) method, in which case it would be:

```python
cfg = parser.parse_args()
cfg_init = parser.instantiate_classes(cfg)
```

The good thing about `instantiate_classes` is that it will work when you have a parser with many (possibly nested) classes. And when you link arguments between classes, it will automatically determine the topological order needed to instantiate them.

There are three more manual ways of doing this. The elements such as `__path__` are considered metadata and there are ways to disable/remove them. One is when creating the parser, i.e. `parser = ArgumentParser(default_meta=False)`. Another is when actually parsing, i.e. `parser.parse_args(with_meta=False)`. And finally there is a function to remove them, i.e. `jsonargparse.strip_meta(cfg)`.
