### ISSUE TITLE
Question about parse_known_args

### ISSUE THREAD

**Issue by jannea** [omni-us/jsonargparse#139]
How to do something like this with the jsonargparse without `parser.parse_known_args()?` 

```
from argparse import ArgumentParser

if __name__ == "__main__":
    parser = ArgumentParser()

    parser.add_argument("--option", type=int)
    args, _ = parser.parse_known_args()

    if args.option == 1:
        parser.add_argument("--x", type=int)
    elif args.option == 2:
        parser.add_argument("--x", type=int)
        parser.add_argument("--y", type=int)
    args = parser.parse_args()
    print(args)
```

**Comment by mauvilsa** [comment]
I would say that this is not a good design for a CLI. How are the users supposed to learn to use it? With that parser if you do `cli.py --help` only the `--option` is shown in the help. There is no way to know that with different values given to `--option` additional arguments become available. And there is no way to get the help showing these added arguments.

Without knowing more about the use case it is difficult to say what would be a good approach. Generally when there are different arguments depending on one value, this is done with [subcommands](https://jsonargparse.readthedocs.io/en/stable/#sub-commands). Applying it to the case above a user could do `cli.py option1 --help` or `cli.py option2 --help`, i.e. there would be two subcommands `option1` and `option2`. If a user does `cli.py --help` all the available subcommands are shown.

**Comment by mauvilsa** [comment]
@jannea, was my response useful? Do you still believe that in your use case you need `parse_known_args`?
