### ISSUE TITLE
"Component not supported" with unused kwargs

### ISSUE THREAD

**Issue by cifkao** [omni-us/jsonargparse#141]
## 🐛 Bug report

After upgrading from 4.9.0 to 4.10.0, I'm getting a "Component not supported" error due to this assertion failing:
https://github.com/omni-us/jsonargparse/blob/a7cd6720c757196fe71a5c82464026569ed61c21/jsonargparse/parameter_resolvers.py#L330

This is a breaking change because the same code was working fine with 4.9.0.

### To reproduce

```python
import jsonargparse

class F:
    @staticmethod
    def f(x: int = 0):
        pass

class A:

    def __init__(self, **kwargs):
        getattr(F, "f")(**kwargs)

parser = jsonargparse.ArgumentParser()
parser.add_subclass_arguments(A, "a")
parser.parse_object({"a": {"class_path": "__main__.A", "init_args": {}}})
```

Note that I'm not actually trying to use the `**kwargs`, so this would work fine with 4.9.0.

Error:
```pytb
Traceback (most recent call last)
[/usr/local/lib/python3.7/dist-packages/jsonargparse/typehints.py](https://localhost:8080/#) in adapt_typehints(val, typehint, serialize, instantiate_classes, prev_val, append, sub_add_kwargs)
    649             val['class_path'] = get_import_path(val_class)
--> 650             val = adapt_class_type(val, serialize, instantiate_classes, sub_add_kwargs, prev_val=prev_val)
    651         except (ImportError, AttributeError, AssertionError, ParserError) as ex:

... (24 frames)

AssertionError: Component not supported: Call(func=Call(func=Name(id='getattr', ctx=Load()), args=[Name(id='F', ctx=Load()), Str(s='f')], keywords=[]), args=[], keywords=[keyword(arg=None, value=Name(id='kwargs', ctx=Load()))])

The above exception was the direct cause of the following exception:

ValueError                                Traceback (most recent call last)
ValueError: Problem with given class_path "__main__.A":
  - Component not supported: Call(func=Call(func=Name(id='getattr', ctx=Load()), args=[Name(id='F', ctx=Load()), Str(s='f')], keywords=[]), args=[], keywords=[keyword(arg=None, value=Name(id='kwargs', ctx=Load()))])

The above exception was the direct cause of the following exception:

TypeError                                 Traceback (most recent call last)
TypeError: Parser key "a": Problem with given class_path "__main__.A":
  - Component not supported: Call(func=Call(func=Name(id='getattr', ctx=Load()), args=[Name(id='F', ctx=Load()), Str(s='f')], keywords=[]), args=[], keywords=[keyword(arg=None, value=Name(id='kwargs', ctx=Load()))])

The above exception was the direct cause of the following exception:

TypeError                                 Traceback (most recent call last)
TypeError: Configuration check failed :: Parser key "a": Problem with given class_path "__main__.A":
  - Component not supported: Call(func=Call(func=Name(id='getattr', ctx=Load()), args=[Name(id='F', ctx=Load()), Str(s='f')], keywords=[]), args=[], keywords=[keyword(arg=None, value=Name(id='kwargs', ctx=Load()))])
```

(In my actual use case, the error was less helpful (no traceback) because the type that was causing the problem was the type of an argument to another class.)

### Expected behavior

Ideally fall back to the old resolution behavior (which lets you get away with unresolved `**kwars` as long as you don't try to use them).

Otherwise, I would appreciate at least an error message that would help get rid of the problem. Currently I have no idea how to solve this other than to revert to `jsonargparse<4.10.0`.

### Environment

- jsonargparse version: 4.10.0
- Python version: 3.7.13
- How jsonargparse was installed: `pip install jsonargparse==4.10.0`
- OS: Linux

**Comment by mauvilsa** [comment]
Thank you for reporting! Is this pattern `getattr(F, "f")(**kwargs)` used in some popular library? If so, which one? I want to know to understand if it makes sense to extend the AST resolving to consider this case.

**Comment by cifkao** [comment]
No, I haven't seen this pattern anywhere. My actual code is something like:
```python
proxy = getattr(manager, cls.__name__)(*args, **kwargs)
```
where `manager` is an instance of `multiprocessing.managers.BaseManager`.

**Comment by mauvilsa** [comment]
> No, I haven't seen this pattern anywhere.

Then for the time being the AST resolver will not be extended to cover this case. The bug was fixed a few days ago so will close this issue now. Will release this in a bit.
