### ISSUE TITLE
Path_u doesn't support file protocol on Windows

### ISSUE THREAD

**Issue by RoryDungan** [omni-us/jsonargparse#144]
## 🐛 Bug report

I have an argument of type `Path_u`. When I pass a file protocol URL to a file that I know does exist I get an error saying "File does not exist". The issue only seems to happen on Windows. 

### To reproduce

Example code:
```
from jsonargparse import ArgumentParser
from jsonargparse.typing import path_type

parser = ArgumentParser()
parser.add_argument("--path", type=path_type("u"))

args = parser.parse_args()

print(f"path: {args.path}")
```
To run:
```
python example.py --path "file:///C:/Users/r_dungan/dev/test/file_protocol_test/example.py"
```
This resulted in the following output:
```
usage: example.py [-h] [--path PATH]
example.py: error: Configuration check failed :: Parser key "path": Not of type Path_u. File does not exist: /C:/Users/r_dungan/dev/test/file_protocol_test/example.py
```

This seems to be a result of the logic at [util.py:408](https://github.com/omni-us/jsonargparse/blob/master/jsonargparse/util.py#L408) that replaces `file:///` with `/` before checking if the file exists. This works fine on Unix-like platforms but on windows it results in an extra "/" at the beginning of the path before the drive letter, which makes it invalid.

### Expected behavior
The path should be picked up by JsonArgParse with no errors. On Linux, this happens as long as the file exists:
```
$ python3 example.py --path file:///mnt/c/Users/r_dungan/dev/test/file_protocol_test/example.py
path: file:///mnt/c/Users/r_dungan/dev/test/file_protocol_test/example.py
```

### Environment
- jsonargparse version: 4.10.2
- Python version: 3.10.5, 3.9.10
- How jsonargparse was installed: `pip install jsonargparse`, `poetry install jsonargparse`
- OS: Windows 10 21H2

**Comment by mauvilsa** [comment]
Would you like to create a pull request with the fix?

**Comment by mauvilsa** [comment]
Fixed in https://github.com/omni-us/jsonargparse/commit/af9e6dfb57e736a3092e6ad2e47ca41c4a5fee27.
