### ISSUE TITLE
Mypy fails to find jsonargparse type hints

### ISSUE THREAD

**Issue by psirenny** [omni-us/jsonargparse#151]
## 🐛 Bug report

Mypy command can't find jsonargparse library types:

```sh
mypy --namespace-package --explicit-package-bases model
```
<img width="967" alt="Screen Shot 2022-07-25 at 10 24 38 AM" src="https://user-images.githubusercontent.com/463178/180801848-e1d496a1-28d4-452f-9fe1-bae9705cf6d2.png">

### To resolve

Adding a blank **py.typed** file to the jsonargparse module resolves the error (locally). See [py-typed marker file](https://mypy.readthedocs.io/en/stable/running_mypy.html#missing-library-stubs-or-py-typed-marker).

### Environment

- OS: Mac OS 12.4
- Python 3.9.10 installed with pyenv
- Dependencies installed with Poetry:
  * jsonargeparse@4.12.0
  * mypy@0.782

**Comment by mauvilsa** [comment]
@psirenny will you open a pull request for this? Apart from adding the `py.typed` file, the `[options.package_data]` section in `setup.cfg` needs to be updated so that the file gets included in the whl package.

**Comment by psirenny** [comment]
I created a pull request here: https://github.com/omni-us/jsonargparse/pull/152.
