### ISSUE TITLE
AST resolver - support super with arbitrary parameters

### ISSUE THREAD

**Issue by t-mesq** [omni-us/jsonargparse#153]
## 🚀 Feature request

Currently (`v4.12.0`) the AST resolver fails when resolving  calls to super that don't follow the immediate MRO (i.e., `super(SubClass, self)` for class `SubSubClass(SubClass)`). This used to be possible in `<=v4.9.0`, so would it be possible for AST resolver to handle these cases?

### To reproduce

```python
from jsonargparse import ArgumentParser

class BaseClass:
    def __init__(self, base_arg: int, *args, base_kwarg: str="base", **kwargs):
        self.base_arg = base_arg
        self.base_kwarg = base_kwarg

class SubClass(BaseClass):
    def __init__(self, *args, sub_kwarg: str="sub", **kwargs):
        super().__init__(*args, **kwargs)
        self.sub_kwarg = sub_kwarg

class SubSubClass(SubClass):
    def __init__(self, *args, subsub_kwarg: str="subsub", **kwargs):
        super(SubClass, self).__init__(*args, **kwargs). # <- 
        self.subsub_kwarg = subsub_kwarg

config = {"class_path": "SubSubClass", "init_args": {"base_arg": 3}}
parser = ArgumentParser()
parser.add_argument('--myclass', type=BaseClass)
print(parser.parse_args(["--myclass", str(config)]))
```

Running the script in `v4.9.0` results in:
```python
Namespace(myclass=Namespace(class_path='__main__.SubSubClass', init_args=Namespace(base_arg=3, base_kwarg='base', sub_kwarg='sub', subsub_kwarg='subsub')))
```
which is a valid initialisation for `SubSubClass`, though `sub_kwarg` isn't necessary.
In `v4.12.0` (with `JSONARGPARSE_DEBUG` enabled), however, it results in an error:
```
...
2022-07-27 11:59:33,895 - ArgumentParser - DEBUG - AST resolver: super with arbitrary parameters not supported: Call(func=Attribute(value=Call(func=Name(id='super', ctx=Load()), args=[Name(id='SubClass', ctx=Load()), Name(id='self', ctx=Load())], keywords=[]), attr='__init__', ctx=Load()), args=[Starred(value=Name(id='args', ctx=Load()), ctx=Load())], keywords=[keyword(arg=None, value=Name(id='kwargs', ctx=Load()))])
2022-07-27 11:59:33,902 - ArgumentParser - ERROR - 'Configuration check failed :: No action for destination key "base_arg" to check its value.'
2022-07-27 11:59:33,906 - ArgumentParser - ERROR - Parser key "myclass": Problem with given class_path "__main__.SubSubClass":
...
```
### Expected behavior
If possible, I would expect the previous script to produce:
```python
Namespace(myclass=Namespace(class_path='__main__.SubSubClass', init_args=Namespace(base_arg=3, base_kwarg='base', subsub_kwarg='subsub')))
```
### Environment

- jsonargparse version: 4.12.0
- Python version: 3.9
- How jsonargparse was installed: `pip install jsonargparse`
- OS: Linux

Thank you in advance!

**Comment by mauvilsa** [comment]
Thank you for reporting. In `v4.9.0` the fact that `sub_kwarg` is in the namespace is not just about being unnecessary. If `BaseClass` didn't have `**kwargs`, it would fail on instantiation, i.e.
```python
>>> cfg = parser.parse_args(["--myclass", str(config)])
>>> parser.instantiate_classes(cfg)
...
TypeError: __init__() got an unexpected keyword argument 'sub_kwarg'
```
Super with arbitrary parameters wasn't supported in `v4.9.0` and it isn't supported in `v4.12.0`. This isn't really a bug, but a feature request. Changing the labels accordingly.

**Comment by mauvilsa** [comment]
This new feature has been implemented in commit https://github.com/omni-us/jsonargparse/commit/1751fe7f213386cb54a52c8a32e1a2201cffab66.

**Comment by t-mesq** [comment]
Thank you for getting on this so quickly!
