### ISSUE TITLE
Easy way to add CLI arguments to existing function?

### ISSUE THREAD

**Issue by iiwolf** [omni-us/jsonargparse#155]
Hello, thank you for your hard work on this library, I find it very useful!

Apologies if this is in documentation or in issues, I searched but could not find anything accomplishing exactly what I wanted to do.

Essentially, I just wanted a way to easily and robustly add arguments to an existing function. Usually this is because I have a data processing function that returns a `pd.DataFrame`, but when using the CLI I want to be able to accept an argument for where to write out the data. Or in a similar vein, when plotting something with Plotly, I have a function that returns a `fig` and want to allow the user to output to png or html. 

I was able to implement this in the following example, but it is fragile and wordy. I want to be able to easily do this for ~20 different functions with slightly different needs.

```python
#!/usr/bin/env python3
# cli_test.py
from jsonargparse import CLI
import pandas as pd
import sys

# df processing function
def dataframe_processing_function(column: str, data: float):
    return pd.DataFrame(columns=[column], data=[data])

if __name__ == "__main__":

    # <--Easier way to do this?-->
    if sys.argv[-2] == "--output":
        output_file = sys.argv[-1]
        sys.argv = sys.argv[:-2]
    else:
        output_file = 'mass.csv'
    
    # Call function and save to csv
    df = CLI(dataframe_processing_function)
    df.to_csv(output_file, index=False)
```

Then example use would be

```bash
$ cli_test.py mass 3.2
$ cli_test.py mass 3.2 --output mass_info.csv
```

I am thinking there is some magic I can do with `capture_parser` and `ArgumentParser`, but I couldn't get anything to work correctly. I know the _simplest_ solution is probably adding that `output` argument to my function, but this is for an existing framework that is pretty tidy and I'd rather not add to it like that. IMO output a dataframe to file _and_ returning it feels like breaking the Unix principle of everything does one thing and does it well.

Alternatively, I thought to wrap `dataframe_processing_function` and adding the additional argument, but then I have to explicitly list out the arguments and their types, defeating the purpose of using this library.

Appreciate any and all feedback. Thank you very much!

Isaac

**Comment by mauvilsa** [comment]
Thank you for the interest! The wrap function would be the way to go. There is no need to duplicate the parameters of the wrapped function. Essentially your example would change to:
```python
from jsonargparse import CLI
import pandas as pd

def dataframe_processing_function(column: str, data: float):
    return pd.DataFrame(columns=[column], data=[data])

def dataframe_processing_function_with_output(*args, output_file: str, **kwargs):
    df = dataframe_processing_function(*args, **kwargs)
    df.to_csv(output_file, index=False)

if __name__ == "__main__":
    CLI(dataframe_processing_function_with_output)
```

**Comment by mauvilsa** [comment]
You can read about why using `*args` and `**kwargs` works and other supported cases in https://jsonargparse.readthedocs.io/en/latest/#ast-resolver.
