### ISSUE TITLE
PrintConfigAction added twice

### ISSUE THREAD

**Issue by florianblume** [omni-us/jsonargparse#169]
## 🐛 Bug report

I use jsonargparse with Pytorch Lightning which crashes when I try to add another config argument in a class derived from PL's CLI. I added the new config argument like this

```python
parser.add_argument('--slurm', action=ActionConfigFile)
```
and now it crashes on [this line](https://github.com/omni-us/jsonargparse/blob/master/jsonargparse/core.py#L108) with the following error message

    argparse.ArgumentError: argument --print_config: conflicting option string: --print_config

Modifying the line from

```python
if isinstance(action, ActionConfigFile) and getattr(self, '_print_config', None) is not None:
```
to
```python
if isinstance(action, ActionConfigFile) and getattr(self, '_print_config', None) is None:
```
(i.e. remove the `not`) solves this. Intuitively, I'd say this is what the line was supposed to be or am I mistaking something?

### To reproduce

I tried to make a reproducible example without PL but it wouldn't work and I thought I first ask whether that's a mistake before spending further time creating one. If you need one, let me know, then I'll try again.

### Expected behavior

The `ActionConfigFile` argument should be addable without the error to happen.

### Environment

- jsonargparse version: `4.13.0`
- Python version: `3.8.13`
- How jsonargparse was installed: `pip install jsonargparse[signatures]`
- OS (e.g., Linux): CentOS Linux on the university's cluster but also happens on Ubuntu

**Comment by florianblume** [comment]
Ok weird, on the cluster this solution actually doesn't work but on my local machine it does. I'll investigate this more, sorry that I opened the issue to early!

**Comment by mauvilsa** [comment]
`ActionConfigFile` is not intended to be used more than once in a parser. Maybe it should give an error when someone tries to add a second one with a more useful message. What exactly is it that you are trying to achieve? Just guessing, but maybe what you want is:

```python
parser.add_argument('--slurm', type=dict, enable_path=True)
```

**Comment by florianblume** [comment]
Hey, thanks for your quick reply! I'm trying to achieve that I can pass the path to a configuration file and it is automatically parsed. So I do something like `--slurm configs/slurm/v100s.yml`. I didn't know you weren't supposed to use `ActionConfigFile` twice, it looked like you can use it that way [in the docs](https://jsonargparse.readthedocs.io/en/stable/index.html#configuration-files). But maybe that was a misconception because PL adds options for `--model` and `--data` and I assumed there were also of type `ActionConfigFile`. I'll try what you suggested.

**Comment by mauvilsa** [comment]
Adding an argument with type `dict` as I said would load from a config file. Though it would accept anything, i.e., no validation. If you want validation then you could use as type a dataclass. In lightning for the `--model` and `--data` cases the argument is added a bit differently, see [cli.py#L123-L129](https://github.com/Lightning-AI/lightning/blob/7fed7a12c56c6b0e08f0223f68d7d311ea7ac90f/src/pytorch_lightning/cli.py#L123-L129). But internally uses the same action as the `enable_path=True`, which is different to `ActionConfigFile`.

Indeed this is not explained well in the docs.

**Comment by florianblume** [comment]
Ok thanks got it! It works now.
