### ISSUE TITLE
Support dataclasses.field as the default value

### ISSUE THREAD

**Issue by carmocca** [omni-us/jsonargparse#17]
`field` is necessary for dataclasses with mutable fields. However, jsonargparse fails to validate them:

```python
import dataclasses
from typing import List
import jsonargparse

@dataclasses.dataclass
class Foo:
    # the default value cannot be a mutable
    # object so a field has to be used
    bar: List[str] = dataclasses.field(default_factory=lambda: ["foo"])

# this works
Foo()
# also with a value
Foo(bar=["foo", "bar"])

parser = jsonargparse.ArgumentParser()
parser.add_class_arguments(Foo)

# this also works
args = parser.parse_args(["--bar=[foo,bar]"], with_meta=False)
print(args) # Namespace(bar=['foo', 'bar'])

# but not without a value
parser.parse_args()
"""
Traceback (most recent call last):
  File "/home/python3.8/site-packages/jsonargparse/core.py", line 867, in check_config
    check_values(cfg)
  File "/home/python3.8/site-packages/jsonargparse/core.py", line 855, in check_values
    self._check_value_key(action, val, kbase, ccfg)
  File "/home/python3.8/site-packages/jsonargparse/core.py", line 1014, in _check_value_key
    value = action._check_type(value, cfg=cfg)  # type: ignore
  File "/home/python3.8/site-packages/jsonargparse/jsonschema.py", line 117, in _check_type
    raise TypeError('Parser key "'+self.dest+'"'+elem+': '+str(ex))
TypeError: Parser key "bar": <factory> is not of type 'array'

Failed validating 'type' in schema:
    {'items': {'type': 'string'}, 'type': 'array'}

On instance:
    <factory>
"""
```

If we avoid validation by adding `Any`, no exception is raised but it does not contain the correct default value:

```python
import dataclasses
from typing import List, Union, Any
import jsonargparse

@dataclasses.dataclass
class Foo:
    # Any added to avoid validating it
    bar: Union[List[str], Any] = dataclasses.field(default_factory=lambda: ["foo"])

parser = jsonargparse.ArgumentParser()
parser.add_class_arguments(Foo)
args = parser.parse_args(with_meta=False)
print(args)  # Namespace(bar=<factory>)
print(type(args.bar))  # <class 'dataclasses._HAS_DEFAULT_FACTORY_CLASS'>
```

Any idea on how to support this? Or a valid workaround?

Sorry for giving you so much work haha. Im currently working on updating [PyLaia](https://github.com/carmocca/PyLaia/tree/jsonargparse) to use jsonargparse so trying to report back all the rough edges I find along the way!

**Comment by mauvilsa** [comment]
> Sorry for giving you so much work haha. Im currently working on updating [PyLaia](https://github.com/carmocca/PyLaia/tree/jsonargparse) to use jsonargparse so trying to report back all the rough edges I find along the way!

No problem. In fact I am grateful. One of the expected benefits of open source is to get feedback, figure out better ways to do things and find bugs. Funny you mention PyLaia. Among the reasons why I started jsonargparse in the first place was because of Laia and PyLaia. I simply thought there was too much non-reusable code for parsing arguments there.

**Comment by mauvilsa** [comment]
Is it strictly necessary for you that the default is a list? To make it immutable it could be a tuple so it would be

```python
@dataclasses.dataclass
class Foo:
    bar: Union[List[str], Tuple[str]] = ("foo",)
```

Right now I am not sure how it could be done for dict default values.

**Comment by mauvilsa** [comment]
Adding support for dataclasses.field I think should be rather simple. I will look at it.

**Comment by carmocca** [comment]
Yes, this works in the meantime :+1:

**Comment by mauvilsa** [comment]
This is now supported.
