### ISSUE TITLE
Cannot override Callable init_args without passing the class_path

### ISSUE THREAD

**Issue by tshu-w** [omni-us/jsonargparse#174]
## 🐛 Bug report

Unlike the class argument, I cannot override `Callable` argument without passing the class_path even it is given previously.

### To reproduce

```python
from jsonargparse import CLI
from typing import Callable

def call():
    print("Hi")

class Call:
    def __init__(self, name: str):
        self.name = name

    def __call__(self):
        print(f"Hi, {self.name}")

def fn(
    callable: Callable = call,
):
    callable()

if __name__ == "__main__":
    CLI(fn)
```

```yaml
callable:
  class_path: __main__.Call
  init_args:
    name: Alice
```

```console
python test.py --config test.yaml
Hi, Alice
python test.py --config test.yaml --callable.name Bob
usage: test.py [-h] [--config CONFIG] [--print_config [={comments,skip_null,skip_default}+]] [--callable CALLABLE]
test.py: error: Unrecognized arguments: --callable.name Bob
```

### Expected behavior

```console
python test.py --config test.yaml
Hi, Alice
python test.py --config test.yaml --callable.name Bob
Hi, Bob
```

### Environment

- jsonargparse version: 4.15.1
- Python version: 3.9
- How jsonargparse was installed: `pip install jsonargparse`
- OS (e.g., Linux): macOS & Linux

**Comment by mauvilsa** [comment]
I created a pull request #175. Can you please test and review.

**Comment by tshu-w** [comment]
Perhaps it would be better for `is_callable_typehint` to decide whether to check all subtypes as `is_subclass_typehint` does.
https://github.com/omni-us/jsonargparse/blob/04383f9d38d4096b7d149c8a4d2d57d21d521438/jsonargparse/typehints.py#L237-L240

**Comment by mauvilsa** [comment]
Since you commented here, I thought you were not going to review the pull request, so I merged it. Your comment is spot on. Would you like to create a pull request with the changes?

**Comment by tshu-w** [comment]
Sorry, I didn't realize it when I reviewed the code the first time.

> Would you like to create a pull request with the changes

Sure, do you think it's necessary to add another test about this?

**Comment by mauvilsa** [comment]
> Sure, do you think it's necessary to add another test about this?

Yes, would be good to have a separate test for this.
