### ISSUE TITLE
Remove the NotImplementedError from parse_known_args

### ISSUE THREAD

**Issue by Erotemic** [omni-us/jsonargparse#180]
## 🚀 Feature request

While working on #179 I noticed that `parse_known_args` seems to be implemented correctly, it just prevents the user from running it because users could shoot themselves in the foot. 

I agree that end-applications _should_ not use `parse_known_args`, I think it is a mistake to just remove it from the API for a few reasons: 

1. Compatibility with the `argparse` API. This behavior means that this library can't be used as a drop-in replacement in this corner case.
2.  Using `parser.parse_known_args` is useful when hacking. In the past I've had a populated sys.argv and I needed to get a subset of it that agreed with an argument parser. Not having this function makes that a lot harder.

I can understand not supporting this case if it would require extra implementation effort, but currently the code seems to go out of its way to raise an error when the reset of the codepath seems to be implemented correctly (correct me if I'm wrong). While preventing shoeguns is laudable, API compatibility seems more important IMO.

I can see a few ways forward with various levels of compromise: 

1. Mark the issue as wontfix and close it. I'd be sad, but I'll live.
2. Raise the error by default, but allow the user to set some environment setting or class variable that lets them override it if they want. I'm not a big fan of this, but I like it more than option 1.
3. Similar to option2, but let the user set some environment, class, or module flag that indicates they want to opt-in and operate in "strict" mode and raise the error. This is reasonable, but also seems roundabout.
4. Emit a warning instead of an error. Probably the best compromise if the maintainers feel very strongly about this. The user could go out of their way to suppress it, but they are at least warned they are doing it wrong. 
5. Just remove the error. This is my preference, I think the decision to use `parse_known_args` is enough of an opt-in that the user is willing to accept the risk of typos. Discouragement should go in the documentation.

**Comment by mauvilsa** [comment]
> I can understand not supporting this case if it would require extra implementation effort, but currently the code seems to go out of its way to raise an error when the reset of the codepath seems to be implemented correctly (correct me if I'm wrong).

That would depend on what "implemented correctly" means. To me, way more important than supporting argparse API is that **all** the features that are supported in jsonargparse work seamlessly together. I guess you only did the most simple test. Commenting out the `raise`, several things can be observed to not work as expected:

```python
from jsonargparse import ArgumentParser, ActionConfigFile

parser = ArgumentParser()
parser.add_argument('--config', action=ActionConfigFile)
parser.add_argument('--a', type=int, default=1)

cfg, unk = parser.parse_known_args(['--a=2', '--b=x'])
print(cfg)
# gives: Namespace(a=2)
# incorrectly missing 'config' key
print(unk)
# gives: ['--b=x']
# okay

value = {
    'a': 3,
    'b': 'y',
}
cfg, unk = parser.parse_known_args([f'--config={value}'])
print(cfg)
# gives: Namespace(a=3, b='y', config=[None])
# incorrectly includes 'b' key
print(unk)
# gives: []
# incorrectly empty

parser = ArgumentParser()
parser.add_argument('--n.a1', type=int)
parser.add_argument('--n.a2', type=int)
parser.add_argument('--config', action=ActionConfigFile)
cfg, unk = parser.parse_known_args(['--n.a1=3', '--n.a2=4', '--n.a3=5'])
print(cfg)
# gives: Namespace(n=Namespace(a1=3, a2=4))
# incorrectly missing 'config' key
print(unk)
# gives: ['--n.a3=5']
# okay

value = {
    'n': {
        'a1': 3,
        'a2': 4,
        'a3': 5,
    }
}
cfg, unk = parser.parse_known_args([f'--config={value}'])
print(cfg)
# gives: Namespace(config=[None], n=Namespace(a1=3, a2=4, a3=5))
# incorrectly includes 'n.a3' key
print(unk)
# gives: []
# incorrectly empty

class Class:
    def __init__(self, p1: int, p2: int):
        pass

parser = ArgumentParser()
parser.add_class_arguments(Class, 'm')
parser.add_argument('--config', action=ActionConfigFile)
value = {
    'm': {
        'p1': 3,
        'p2': 4,
        'p3': 5,
    }
}
cfg, unk = parser.parse_known_args([f'--config={value}'])
init = parser.instantiate_classes(cfg)
# fails with TypeError: __init__() got an unexpected keyword argument 'p3'


cfg, unk = parser.parse_known_args(['--a=2', '--c=x'])
# fails because --c considered shorthand of --config
```

Apart from these fast tests, more things for sure or very likely don't work: subcommands, population of defaults, argument linking, print config, capturing the parser, parsing environment variables, validation in some cases. Therefore, I am sorry to say that this is a won't do.

**Comment by Erotemic** [comment]
Thanks for the explanation. The reasoning makes sense. Closing.
