### ISSUE TITLE
Crashing when using set typehint with specified dtype (e.g. set[int])

### ISSUE THREAD

**Issue by Andry-Bal** [omni-us/jsonargparse#183]
## 🐛 Bug report

When using typehint for _set_ with specified in _[]_ dtype, crashes with the following exception:

`  File "jsonargparse/typehints.py", line 542, in adapt_typehints
    subtypehint = subtypehints[0 if is_ellipsis else n]
IndexError: tuple index out of range`

### To reproduce
```
from jsonargparse import ArgumentParser


def f(a: set[int]):
    print(a)


if __name__ == '__main__':
    parser = ArgumentParser(error_handler=None)
    parser.add_function_arguments(function=f)
    parser.parse_args([f"--a=[1,2,3]"])
```

### Expected behavior

List passed through a terminal or config file should be parsed into a python _set_ with dtype specified in _[]_ (analogously to how it is done with other container types supported by jsonargparse).

### Environment
- jsonargparse version (e.g., 4.8.0): 4.15.2
- Python version (e.g., 3.9): 3.10.6
- How jsonargparse was installed (e.g. `pip install jsonargparse[all]`): pip install jsonargparse[all]
- OS (e.g., Linux): Linux

**Comment by mauvilsa** [comment]
Thank you for reporting! Do you want to create a pull request for this?

**Comment by mauvilsa** [comment]
Fixed in commit https://github.com/omni-us/jsonargparse/commit/55e00ffedba287e9421495348acd4d35da1d23d8.
