### ISSUE TITLE
Basic Usage example from docs not accurate

### ISSUE THREAD

**Issue by roschly** [omni-us/jsonargparse#188]
## 📚 Documentation improvement
The basic usage example from the docs (https://jsonargparse.readthedocs.io/en/stable/index.html#basic-usage) does not work w.r.t. showing parameter descriptions in `--help` message.

With the `example.py` file:
```python
from jsonargparse import CLI

def command(
    name: str,
    prize: int = 100
):
    """Prints the prize won by a person.

    Args:
        name: Name of winner.
        prize: Amount won.
    """
    print(f'{name} won {prize}€!')

if __name__ == '__main__':
    CLI()
```
using `jsonargparse==4.16.0` on windows, I do NOT get this
```
$ python example.py --help
...
Prints the prize won by a person:
  name                  Name of winner. (required, type: str)
  --prize PRIZE         Amount won. (type: int, default: 100)
```
but instead this
```
usage: example.py [-h] [--config CONFIG] [--print_config [={comments,skip_null,skip_default}+]] [--prize PRIZE] name

optional arguments:
  -h, --help            Show this help message and exit.
  --config CONFIG       Path to a configuration file.
  --print_config [={comments,skip_null,skip_default}+]
                        Print the configuration after applying all other arguments and exit.

<function command at 0x00000203EB1251F0>:
  name                  (required, type: str)
  --prize PRIZE         (type: int, default: 100)
```

**Comment by mauvilsa** [comment]
Thank you for reporting! You are correct that the documentation is not clear in that part. The parsing of docstrings is an optional features. To get the correct output you need to install as `pip install "jsonargparse[signatures]"`, see [installation](https://jsonargparse.readthedocs.io/en/stable/#installation). I will add a note to the example to make this clear.

**Comment by mauvilsa** [comment]
Improved the documentation in commit https://github.com/omni-us/jsonargparse/commit/fef2fa736f9ca1c0b48a59e971c6c0246e6ee76c and the new version can be seen in https://jsonargparse.readthedocs.io/en/latest/#basic-usage.
