### ISSUE TITLE
Default values can't look like `{{something}}`

### ISSUE THREAD

**Issue by dconathan** [omni-us/jsonargparse#189]
## 🐛 Bug report

Default values can't look like `{{something}}`

### To reproduce

```python
import jsonargparse

# Here define one or more functions or classes
def func1(param1: str="{{something}}"):
    ...

# Run the CLI providing the components
jsonargparse.CLI([func1], error_handler=None)
```
Invoking this fails with a long traceback that looks like something related to encoding the default value as yaml?  

```
    raise ConstructorError("while constructing a mapping", node.start_mark,
yaml.constructor.ConstructorError: while constructing a mapping
  in "<unicode string>", line 1, column 1
found unhashable key
  in "<unicode string>", line 1, column 2
```

My guess is because if this is a value in yaml it looks like you're trying to build a dict with a dict as a key.  Is there a workaround for this?  My use case is I want to pass in jinja template-like things.

### Expected behavior

The CLI would run without error.

### Environment

- jsonargparse version (e.g., 4.8.0): 4.16.0
- Python version (e.g., 3.9): 3.10
- How jsonargparse was installed (e.g. `pip install jsonargparse[all]`): pip install jsonargparse
- OS (e.g., Linux): MacOS

**Comment by mauvilsa** [comment]
Thank you for reporting! I just pushed a fix for this in commit https://github.com/omni-us/jsonargparse/commit/72672b4e026da688d5e8a05204fdfa13bf9d3478.

**Comment by dconathan** [comment]
Thanks!
