### ISSUE TITLE
Support Optional[Enum]

### ISSUE THREAD

**Issue by carmocca** [omni-us/jsonargparse#19]
```python
from dataclasses import dataclass
from enum import Enum
from typing import Optional
import jsonargparse

class MyEnum(Enum):
    A = "A"
    B = "B"

@dataclass
class Foo:
    value: Optional[MyEnum] = None

parser = jsonargparse.ArgumentParser()
parser.add_class_arguments(Foo)
args = parser.parse_args(["--value=A"], with_meta=False)
# error: Unrecognized arguments: --value=A
assert args.value is MyEnum.A
```

Works without `Optional`

**Comment by carmocca** [comment]
Also, just as in #20,

`value: MyEnum = None` fails with `'NoneType' object has no attribute 'name'`

**Comment by mauvilsa** [comment]
This is now supported. As a side note, now if you initialize `ArgumentParser` with `logger={'level': 'DEBUG'}` you will see which arguments are skipped and the reason for it.

**Comment by carmocca** [comment]
Works, but the help message does not include the Enum choices when wrapped with Optional.

> As a side note, now if you initialize ArgumentParser with logger={'level': 'DEBUG'} you will see which arguments are skipped and the reason for it.

Nice! That is very helpful

**Comment by carmocca** [comment]
Also, this does not support Enums with data types

```python
from dataclasses import dataclass
from enum import Enum
from typing import Optional
import jsonargparse

class MyEnum(str, Enum):
    A = "A"
    B = "B"

@dataclass
class Foo:
    value: Optional[MyEnum] = None

parser = jsonargparse.ArgumentParser(logger={'level': 'DEBUG'})
parser.add_class_arguments(Foo)
args = parser.parse_args(["--value=B"], with_meta=False)
```

```
2020-11-10 14:09:10,258 - ArgumentParser - DEBUG - Skipping argument "value" from "Foo" because of: Unable to generate schema from annotation typing.Union[__main__.MyEnum, NoneType]
2020-11-10 14:09:10,265 - ArgumentParser - ERROR - Unrecognized arguments: --value=B
usage: scratch_4.py [-h] [--print-config]
scratch_4.py: error: Unrecognized arguments: --value=B
```

This kind of Enums have the benefit of supporting `MyEnum.A == "A"`

**Comment by mauvilsa** [comment]
`class MyEnum(str, Enum)` now works and for `Optional[Enum]` the help includes the choices plus `null`.

**Comment by carmocca** [comment]
> and for `Optional[Enum]` the help includes the choices plus `null`.

Does not seem to work for me. I am using the snippet I wrote in my previous post.

**Comment by mauvilsa** [comment]
Silly me. I fixed it, but then pylint or mypy told me to change some line which broke it.

**Comment by mauvilsa** [comment]
It should be fixed now.
