### ISSUE TITLE
Custom Types documentation

### ISSUE THREAD

**Issue by efanibi25** [omni-us/jsonargparse#195]
As a result of the changes that were made in jsonargparse for parsing types, some of the examples for argparse itself don't work completely.

This is an example from the argparse documentation on how to handle custom types
```
def hyphenated(string):
    return '-'.join([word[:4] for word in string.casefold().split()])

parser = argparse.ArgumentParser()
_ = parser.add_argument('short_title', type=hyphenated)
parser.parse_args(['"The Tale of Two Cities"'])
```

This doesn't work completely in jsonargparse, because when printing the help screen it wants to print the type. The type part of the string just gets garbled into a reference to the memory location of the function. 

Looking through the code there seem to be some complexities in getting a custom type implemented. Namely the use of the metaclass type, and some setup that the code wants implementing when calling the type constructor.

Saying that I notice that there was a function called create_type. It seems to provide all the abstractions required to make a custom_type.

It seems to strike a good balance between having control, and not being overly complicated. However, it currently is not documented. 

This is an example of a test function
```
def interval2()-> Type:
    def check_value(cls, v):

        if v%5!=0:
            raise ValueError(f'This is value is invalid')
    return create_type("interval23",base_type=int,check_value=check_value,extra_attrs={"_type":int})
interval=interval2()
    
```

**Comment by mauvilsa** [comment]
The `create_type` function is not currently part of the public API. But I agree that it makes sense to expose it. I will look into doing this, possibly improving it a bit to better guide developers.

Creation of a type is a requirement if the intention is to use it in type hints in function signatures. Using a simple function as type is supported in jsonargparse, though it requires the function to be idempotent. The `hyphenated` example above is not idempotent, thus leading to bad parsing results, see:

```python
>>> def hyphenated(string):
...     return '-'.join([word[:4] for word in string.casefold().split()])
... 
>>> value = '"The Tale of Two Cities"'
>>> print(value)
"The Tale of Two Cities"
>>> print(hyphenated(value))
"the-tale-of-two-citi
>>> print(hyphenated(hyphenated(value)))  # not idempotent!
"the
```

I will document the requirements for using a function as a type and the creation of types.

**Comment by mauvilsa** [comment]
In pull request #380 I have added the explanation on how to create custom types and exposed `create_type` though now it is called `extend_base_type` and has a docstring. @efanibi25 if you can, please have a look.
