### ISSUE TITLE
AttributeError using --print-config and Enum

### ISSUE THREAD

**Issue by carmocca** [omni-us/jsonargparse#20]
When I create an Enum field:

```python3
from dataclasses import dataclass
from enum import Enum
import jsonargparse

class MyEnum(Enum):
    A = "A"
    B = "B"

@dataclass
class Foo:
    # THIS WORKS
    value: MyEnum = MyEnum.A

    # THIS DOES NOT
    value: MyEnum = "A"
    # File "jsonargparse/core.py", line 620, in cleanup_actions
    # cfg[action.dest] = cfg[action.dest].name
    # AttributeError: 'str' object has no attribute 'name'

parser = jsonargparse.ArgumentParser()
parser.add_class_arguments(Foo)
args = parser.parse_args(with_meta=False)
print(args)
```

`--print-config` fails if the default value is not an `Enum`. Is this a bug or not supported?

The reason I set the default to a `str` instead of `Enum` is because the help message is tidier:

```
# with str
--value {A,B}   my value (default: "A")

# with Enum
--value {A,B}   my value (default: MyEnum.A)
```

In the second case, an user might think he has to pass `--value=MyEnum.A` which wouldn't work.
Maybe the correct fix is not supporting `str` but making the help message use the simpler form.

**Comment by mauvilsa** [comment]
The default value should be `MyEnum.A` not a string since it would have a different type. The help now shows correctly only `A`.
