### ISSUE TITLE
CLI does not work with callable component?

### ISSUE THREAD

**Issue by indigoviolet** [omni-us/jsonargparse#238]
## 🐛 Bug report

CLI currently breaks if I pass in a callable instance instead of a function. It would be nice not to break this abstraction.

### To reproduce
```python
from dataclasses import dataclass

from jsonargparse import CLI


@dataclass
class Foo:
    def __call__(self, x: int):
        return x


if __name__ == "__main__":
    f = Foo()
    CLI(f, as_positional=False)
```

```
❯ python test.py                                
Traceback (most recent call last):
  File "/home/venky/dev/instant-science/name_generator/test.py", line 14, in <module>
    CLI(f, as_positional=False)
  File "/home/venky/dev/instant-science/name_generator/.venv/lib/python3.9/site-packages/jsonargparse/cli.py", line 69, in CLI
    _add_component_to_parser(component, parser, as_positional, fail_untyped, config_help)
  File "/home/venky/dev/instant-science/name_generator/.venv/lib/python3.9/site-packages/jsonargparse/cli.py", line 116, in _add_component_to_parser
    added_args = parser.add_class_arguments(component, **kwargs)
  File "/home/venky/dev/instant-science/name_generator/.venv/lib/python3.9/site-packages/jsonargparse/signatures.py", line 70, in add_class_arguments
    raise ValueError(f'Expected "theclass" parameter to be a class type, got: {theclass}.')
ValueError: Expected "theclass" parameter to be a class type, got: Foo().
```

### Expected behavior

It should work similar to `def foo(x: int)`.

### Environment

- jsonargparse version (e.g., 4.8.0): 4.19
- Python version (e.g., 3.9): 3.9
- How jsonargparse was installed (e.g. `pip install jsonargparse[all]`):  pip install jsonargparse[all]
- OS (e.g., Linux): linux

**Comment by mauvilsa** [comment]
Thank you for reporting!

This would be a feature request instead of a bug, since `CLI` expects either functions or classes, not instances of classes. Also it would be interesting if you explain why do you need to give to `CLI` an instance of a class that becomes callable. I mean, is it that in some use case it makes sense to do this instead of a simple function. Or is it just that if someone does this, it works like if it were a simple function instead of this error.

**Comment by indigoviolet** [comment]
I do have a use case, but it's a long story to lay out all the reasons it is needed; the very truncated summary is that there is a decorator where it is convenient to return a callable class instance instead of another function, because the instance can carry some other associated data as attributes. So I can do `instance()` or `instance.something_else()`.

Another similar argument is the library [wrapt](https://wrapt.readthedocs.io/en/latest/decorators.html) which provides for robust decorators; it ultimately returns a `FunctionWrapper` class. 

Overall in my experience, Python wants to treat an instance with __call__() similar to a function; and it would be nice to not break that "duck typing".

Thanks for jsonargparse, btw. It's pretty nice!

**Comment by mauvilsa** [comment]
Created a pull request that implements the support for callable instances #239. Please review.
