### ISSUE TITLE
Question: Use Function Docstring for `CLI`

### ISSUE THREAD

**Issue by dtoniolo** [omni-us/jsonargparse#245]
First of all, thanks to all the contributors for this awesome package. I begun using it a few days ago and it has already made it way easier for me to write safe and robust CLIs.

I am having an issue with the default behaviour of `jsonargparse.CLI`. More specifically, I have a module which implements a function that is exposed as a CLI through the use of `CLI`. Both the module and the function have a docstring. The first is intended to be seen by the developers, both when they open the file and in the docs generated by Sphinx, while the second is intended to be both the documentation of the function itself and the help for the CLI interface.

The following code snipped provides a minimum working example for my situation:

```python
"""Module docstring."""
from jsonargparse import CLI

def foo(a: int) -> None:
    """Function docsting.

    Parameters
    ----------
    a
        A dummy argument.

    """
    pass


if __name__ == "__main__":
    CLI(foo)
```
Saving this code in a module called `bar.py`, I would expect the output of `python bar.py --help` to be

```
usage: test.py [-h] [--config CONFIG] [--print_config[=flags]] a

Function docstring.

positional arguments:
  a                     A dummy argument. (required, type: int)

options:
  -h, --help            Show this help message and exit.
  --config CONFIG       Path to a configuration file.
  --print_config[=flags]
                        Print the configuration after applying all other
                        arguments and exit. The optional flags customizes the
                        output and are one or more keywords separated by
                        comma. The supported flags are: comments,
                        skip_default, skip_null.
```

but I get the following output

```
usage: test.py [-h] [--config CONFIG] [--print_config[=flags]] a

Module docstring.

positional arguments:
  a                     A dummy argument. (required, type: int)

options:
  -h, --help            Show this help message and exit.
  --config CONFIG       Path to a configuration file.
  --print_config[=flags]
                        Print the configuration after applying all other
                        arguments and exit. The optional flags customizes the
                        output and are one or more keywords separated by
                        comma. The supported flags are: comments,
                        skip_default, skip_null.
```

What is happening is that `CLI` correctly recognizes the arguments of the `foo` function, along with their types and docstrings, but for the description of the command uses the module docstring instead of `foo`'s one. I find this behaviour to be quite conterintuitive and it's not what I'm looking for.

So, my questions would be:
- am I misunderstanding something in the way `jsonargparse` is intended to be used or is my case a valid example?
- Is there a way to use docstring of `foo` in the help of the CLI interface? if yes, how can I do so? I couldn't find any specific info in the documentation.

**Comment by mauvilsa** [comment]
From a first thought I does make more sense to be "Function docstring" instead of "Module docstring". This behavior is hard coded and probably a byproduct of a different case. It could be `CLI([foo1, foo2])` in which case we need a general description (module docstring) and one description for each subcommand (each function's docstring).

A possible modification for the single function case could be: if the function has a docstring with a short description, use that. Otherwise use the module's docstring (current behavior fallback).

**Comment by mauvilsa** [comment]
Actually now I think that better to never use the module's docstring. For that it can be done as `CLI(foo, description=__doc__)`.

**Comment by mauvilsa** [comment]
Changed it in commit https://github.com/omni-us/jsonargparse/commit/2d08e83274ca238f33302fc2d86a81291f28174a.

**Comment by dtoniolo** [comment]
Awesome, thanks a lot!
