### ISSUE TITLE
ArgumentParser(print_config) is hard-coded

### ISSUE THREAD

**Issue by carmocca** [omni-us/jsonargparse#25]
See:

https://github.com/omni-us/jsonargparse/blob/05f7ecf3d8cdab0f262c48125f28d3f16c109310/jsonargparse/core.py#L155-L156

should be:

```python
 if print_config is not None: 
     self.add_argument(print_config, action=_ActionPrintConfig) 
```

**Comment by mauvilsa** [comment]
Thank you! It is fixed now.
