### ISSUE TITLE
CLI modification of dictionary args

### ISSUE THREAD

**Issue by thomasgaudelet** [omni-us/jsonargparse#251]
## 📚 Documentation improvement

I am struggling to find information on how one should proceed to modify elements from dictionary args.

E.g. consider a class whereby one (for simplicity) input is a dictionary with a couple of keys. How should one proceed to change the value of one of the keys from CLI? It works well from a config file (json or yaml), but I would like to know if there's a way to do so from CLI. Simply doing `--class.init_args.dict.key val` used to work with jsonargparse==4.14.1, but now it leads to the error `Expected a <class 'dict'>. Got value: Namespace`.

I have seen the dict_kwargs option, but it doesn't solve the issue for me (I have multiple dictionaries input). I can come up with workarounds, but I'd like to know if it's still supported or not.

**Comment by mauvilsa** [comment]
Started writing a unit test to make sure that this behavior is not broken in the future. It seems to work correctly if `init_args` is excluded, i.e. as `--class.dict.key val`. Though, for consistency it should also work when `init_args` is included. I will fix that.
