### ISSUE TITLE
Error parsing nargs=+ positional argument from config file

### ISSUE THREAD

**Issue by carmocca** [omni-us/jsonargparse#27]
This one is tricky, here is the snippet:

```python
import jsonargparse

parser = jsonargparse.ArgumentParser()
parser.add_argument("--config", action=jsonargparse.ActionConfigFile)
parser.add_argument("my_list", type=str, nargs="+")
args = parser.parse_args()
```

Using the config generated by `--print-config`:
`my_list: null`
the error is:
`error: Parser key "my_list": 'NoneType' object is not iterable`

I believe the correct error should be:
`TypeError: Key "my_list" is required but not included in config object.`

**Comment by carmocca** [comment]
Tried to see if `Optional` would fix it:

```python
parser.add_argument("my_list", type=Optional[str], nargs="+")
```
`error: For ActionJsonSchema with nargs=+ expected value to be list, received: value=None.`


In the meantime, I can use this as a workaround:

```python
parser.add_argument("my_list", type=List[str])
```

but its not quite the same (passing `foo bar` vs `[foo,bar]`)

**Comment by mauvilsa** [comment]
This should be fixed now.
