### ISSUE TITLE
How do I load a simple yaml config file?

### ISSUE THREAD

**Issue by jtlz2** [omni-us/jsonargparse#292]
The below is valid yaml, but when I use `ActionConfigFile`

test.yaml contains:

```
tasks:
  my_task:
    name: my_task
    value: my_value
```

But when I supply this as a config file with `action=ActionConfigFile` it exits with

```
<script_name.py>: error: 'Configuration check failed :: No action for destination key "tasks.my_task.name" to check its value.'
```

When I use OmegaConf, for example, there is no problem when parsing the above.

Is there no way to auto validate yaml like the above without pre-specifying every single type? I just want to load the config yaml above and override it with some command-line values.

Many thanks for such a promising library!

**Comment by mauvilsa** [comment]
For the example above you can do:

```python
from jsonargparse import ActionConfigFile, ArgumentParser

parser = ArgumentParser()
parser.add_argument("--config", action=ActionConfigFile)
parser.add_argument("--tasks.my_task", type=dict)
print(parser.parse_args(["--config=config.yaml"]))
```

Do note that the purpose of the parser is to validate the input and fail early with understandable messages. Also to provide a `--help` option that allows new people to learn how to use a CLI. It is not designed to load any yaml and accept any argument. In fact, it is like this to avoid someone accidentally writing a typo in a config an not noticing immediately.

**Comment by jtlz2** [comment]
@mauvilsa Thank you so much for the speedy reply.

OK it seems this is out of scope in that I have to explicitly specify types - via `add_argument ()`- for all entries in the yaml config.

Thanks again!
