### ISSUE TITLE
Improve the error message when a link function fails

### ISSUE THREAD

**Issue by marianne-omnius** [omni-us/jsonargparse#311]
## 🚀 Feature request

When a link function fails, the error message should give a hint that the error happened when trying to apply a link function.

### Motivation

Currently, the only error message that is displayed is the exception in the link function itself. e.g. `argparse.ArgumentError: 'NoneType' object is not subscriptable`. That makes it very hard to understand what the actual problem is.

### Pitch

Include in the error message that the error happened on linking, and ideally also in which function.

### Alternatives

In my particular case, I had the problem when calling `--print_config` for a `LightningCLI`. In that case, there is no need to call the link functions since the linked arguments are not part of the printed config. So this particular error could maybe be avoided by changing the implementation of printing the config.

**Comment by mauvilsa** [comment]
> I had the problem when calling --print_config for a LightningCLI. In that case, there is no need to call the link functions since the linked arguments are not part of the printed config.

Regarding this, a reproduction script will be needed. I tried with a simple example and the link function is not called when printing the config. Note that in the code, the config print is before applying the links. See:

https://github.com/omni-us/jsonargparse/blob/c4514d49e31b0a5a494273cc647e48f848fe15b4/jsonargparse/_core.py#L308-L311

**Comment by mauvilsa** [comment]
The problem is only when the parser has subcommands. Pull request #381 implements both a better error message when `compute_fn` fails, and not applying parsing links when `--print_config` is requested.
