### ISSUE TITLE
Missing documentation: linked_targets in add_class_arguments()

### ISSUE THREAD

**Issue by noamsgl** [omni-us/jsonargparse#317]
What is the meaning of this argument? How and when would you use, for example? Thanks!
https://github.com/omni-us/jsonargparse/blob/c4514d49e31b0a5a494273cc647e48f848fe15b4/jsonargparse/_signatures.py#L51C13-
L51C13

**Comment by mauvilsa** [comment]
@noamsgl thank you for pointing this out. From what I see that parameter was added in commit https://github.com/omni-us/jsonargparse/commit/30a8235d4389c16c62c843df9a5b57ff9592a399. The `linked_targets` parameter is only necessary for the internal logic of linked arguments. What it does is that when a parameter is required (no default), but it is the target of a link, then that parameter is added as not required and without a default.

I don't see this parameter being useful for anything else apart from this internal usage. I will hide it from the public API.
