### ISSUE TITLE
Support --print_config in subcommands

### ISSUE THREAD

**Issue by mpariente** [omni-us/jsonargparse#33]
It doesn't seem possible to use `--print_config` in subcommands, in fact, it is explicitly removed, why? 
Is there a simple way around it?

**Comment by mauvilsa** [comment]
It is possible. But it is only allowed as a global option and the order matters. It should be run as:

```bash
tool.py --print_config subcommand1 [options1] [subcommand2 [options2] ...]
```

**Comment by mpariente** [comment]
Thanks !
