### ISSUE TITLE
Support for Initialization Arguments from Config Files

### ISSUE THREAD

**Issue by function2-llx** [omni-us/jsonargparse#330]
### Motivation

I'm working with multiple classes where one class (`A`) takes an instance of another class (`B`) as an argument in its initialization. For example:

```python
class B:
	def __init__(self, x: int, y: str):
		pass

class A:
	def __init__(self, b: B):
		pass
```

I want to add A to arguments via `parser.add_class_argument(A, 'a')` and specify `b` in a configuration file, i.e., `--a.b b.yaml` via the command line or `b: b.yaml` in a configuration file for a.

Currently this operation seems infeasible for me as jsonargparse interprets the configuration file path as an import path.

**Comment by mauvilsa** [comment]
> jsonargparse interprets the configuration file path as an import path

I am not sure what you mean by this.

What is described above is already supported. For example, a tool implemented as:

```python
from jsonargparse import ArgumentParser, ActionConfigFile

class B:
    def __init__(self, x: int, y: str):
        pass

class A:
    def __init__(self, b: B):
        pass

parser = ArgumentParser()
parser.add_argument("--config", action=ActionConfigFile)
parser.add_class_arguments(A, "a", sub_configs=True)
parser.parse_args()
```

With a config `a.yaml` as:

```yaml
b:
  class_path: __main__.B
  init_args:
    x: 1
    y: a
```

Then an example that parses using this config would be:

```shell
$ python main.py --a a.yaml --print_config
a:
  b:
    class_path: __main__.B
    init_args:
      x: 1
      y: a
```

With a config `b.yaml` as:

```yaml
class_path: __main__.B
init_args:
  x: 2
  y: b
```

Then an example parsing would be (requires `sub_configs=True`):

```shell
$ python main.py --a.b b.yaml --print_config
a:
  b:
    class_path: __main__.B
    init_args:
      x: 2
      y: b
```

**Comment by function2-llx** [comment]
Hello @mauvilsa , thanks for your detailed response! 

> > jsonargparse interprets the configuration file path as an import path
> 
> I am not sure what you mean by this.

What I meant was that when I don't specify `sub_configs=True`, for example:

```python
from jsonargparse import ArgumentParser

class B:
    def __init__(self, x: int, y: str):
        pass

class A:
    def __init__(self, b: B):
        pass

parser = ArgumentParser()
parser.add_class_arguments(A, 'a')
parser.parse_args(['--a.b', 'b.yaml'])
```
The I get is:
```
usage: main.py [-h] [--a CONFIG] [--a.b.help CLASS_PATH_OR_NAME] --a.b B
main.py: error: Parser key "a.b":
  Problem with given class_path 'b.yaml':
    No module named 'b'
```

My intention is to directly specify a config file containing the content of `init_args` for `b`, in the same way that I specify a config file for `a`. I realize now that I may have misunderstood the process, since `a` is managed by `parser.add_class_argument`, while `b` is a class argument from `a`'s init arguments. It seems that in this case, the init arguments for `b` have to be nested under the `init_args` key. Could you please confirm if my understanding is correct?

**Comment by mauvilsa** [comment]
In python a parameter defined as `b: B` means it expects an instance of `B` or any subclass of `B`. This is why `class_path` and `init_args` is required. If you want it to be only `B`, not subclasses, currently there are two options. Make the class `final` or make it a `dataclass`, see [dataclass-like](https://jsonargparse.readthedocs.io/en/stable/#dataclass-like). For example:

```python
from jsonargparse.typing import final

@final
class B:
    def __init__(self, x: int, y: str):
        pass
```

Currently there is no way to make a generic class act as not subclass when used as a type hint of some particular function signature.
