### ISSUE TITLE
Add multilevel subcommands support to `CLI`

### ISSUE THREAD

**Issue by rusmux** [omni-us/jsonargparse#334]
## 🚀 Feature request

Currently `jsonargparse.CLI` can handle only one level of subcommands through classes. For example:

```Python
from jsonargparse import CLI

class mycli:
    @staticmethod
    def subcommand1(): ...


if __name__ == "__main__":
    CLI(components=[mycli])
```

But there is no easy way to add more subcommands, since embedding a class in another one will cause an error.:

```Python
from jsonargparse import CLI

class mycli:
    @staticmethod
    def subcommand1(): ...

    class subcommand2:
        @staticmethod
        def subsubcommand1(): ...


if __name__ == "__main__":
    CLI(components=[mycli])
```

```Bash
ValueError: Invalid or unsupported input: class=<class '__main__.mycli'>, method_or_property=subcommand2
```

To add more subcommands, you need to use `jsonargparse.ArgumentParser` and implement all the logic manually.

### Motivation

It would be great to be able to create multilevel subcommands easily.

### Pitch

Add multilevel subcommands support to `jsonargparse.CLI`.

**Comment by mauvilsa** [comment]
A clarification. Two levels of subcommands is currently possible by having multiple classes. For example:

```python
from jsonargparse import CLI

class level1_cmd_a:
    @staticmethod
    def level2_cmd_x(): ...

class level1_cmd_b:
    @staticmethod
    def level2_cmd_y(): ...

if __name__ == "__main__":
    CLI(components=[level1_cmd_a, level1_cmd_b])
```

Though, easier ways to implement can be added. For example similar to [`fire.Fire(<dict>)`](https://google.github.io/python-fire/guide/#version-2-firefiredict). Two levels of subcommands could be defined as:

```python
{
    "level1_cmd_a": {
        "level2_cmd_x": func_x,
    },
    "level1_cmd_b": {
        "level2_cmd_y": func_y,
    }
}
```

**Comment by rusmux** [comment]
Oh, yes, I missed it, thank you! But how to add more levels? The `fire` way of doing this seems nice.

**Comment by mauvilsa** [comment]
More than two levels currently is only possible by manually creating the `ArgumentParser`.

**Comment by rusmux** [comment]
Would it be possible to support `fire`-like dictionaries in the future?

**Comment by mauvilsa** [comment]
Yes.

**Comment by rusmux** [comment]
Thank you, will look forward to it!

**Comment by mauvilsa** [comment]
@rusmux @Borda I created a pull request (#346) that implements CLI subcommands via a dict. Please try it out.
