### ISSUE TITLE
nested sub-config files for arguments to signature API functions and class init/methods

### ISSUE THREAD

**Issue by nkrishnaswami** [omni-us/jsonargparse#336]
I’d like to use modular config files for objects of specific types, to facilitate sharing configs across a suite of related tools with different top-level configs.  These are currently using an `ArgumentParser` with `add_function_arguments` and an `ActionConfigParser` for the top-level config.

From the docs, adding argument groups using the signature APIs permits using sub config-files for each group, which I am using, but is there any way to get that configurability a layer or more down, e.g using sub config-files for the individual arguments to a function passed to `add_function_arguments` or similar? (The naive approach of adding `ActionConfigFile`s for the sub-configs did not work.)

If it isn’t supported today, how feasible would it be to add this feature?

**Comment by mauvilsa** [comment]
The signature methods (such as `add_function_arguments`) have the `sub_configs=True` option, which makes subclass types loadable from inner configs. Are you already using this? What other types do you want to be loadable from inner configs? If possible, please provide code snippet examples.

**Comment by nkrishnaswami** [comment]
Oh, I think that's exactly what I need -- not sure how I missed it. I'll take a look, and report back on whether I need anything different. Thanks!

**Comment by nkrishnaswami** [comment]
Looks like my problem was using an ActionConfigFile for the outermost config option: I didn't realize that would be unaware of the `sub_configs` setting for `add_*_arguments`, so I thought the flag meant something else. When I switched to specifying the config file using the `sub_configs`-enabled key, interior config filenames behave like I wanted.  Thanks for the pointer!
