### ISSUE TITLE
ActionParser docs

### ISSUE THREAD

**Issue by mpariente** [omni-us/jsonargparse#34]
Hey,

Sorry for raising many issues but I'm just trying to find out if I'll find my use-case here. 

I think there is an inconsistency in the `ActionParser`'s docs, please correct me if I'm wrong. 

> Sometimes it is useful to take an already existing parser that is required standalone in some part of the code, and reuse it to parse an inner node of another more complex parser. For these cases an argument can be defined using the `ActionParser` class.

and then

> An important detail to note is that the parsers that are given to `ActionParser` are internally modified. So they should be instantiated exclusively for the `ActionParser` and not used standalone.

Should I make a copy then? 

[See here](https://omni-us.github.io/jsonargparse/#parsers-as-arguments)

**Comment by mauvilsa** [comment]
True, it is confusing as it is now. My idea is that you have a function that returns the parser. So this function can be used in one place to parse standalone, and in some other place used to get the parser to give to `ActionParser`. I will modify the docs so that it is clearer.

**Comment by mauvilsa** [comment]
> Sorry for raising many issues but I'm just trying to find out if I'll find my use-case here.

No problem, create as many issues as you need. This is the way to get more perspectives and improve the package further.

**Comment by mpariente** [comment]
> True, it is confusing as it is now. My idea was that you have a function that returns the parser. So this function can be used in one place to get the parser to parse standalone, and in some other place used to get the parser to give to `ActionParser`. I will modify the docs so that it is clearer.

This is clearer indeed. 

> No problem, create as many issues as you need. This is the way to get more perspectives and improve the package further.

I also have this approach but not everyone does, thanks for that.

**Comment by mauvilsa** [comment]
I have improved the description. Please check.

**Comment by mauvilsa** [comment]
This is now in release v3.2.0.
