### ISSUE TITLE
can not fully reproduce python example.py --help

### ISSUE THREAD

**Issue by gmaggi** [omni-us/jsonargparse#347]
Hi,

I am trying to reproduce the example in https://jsonargparse.readthedocs.io/en/v4.23.1/#basic-usage
This shows more information than what is shown in the example `python example.py --help` . Please see attachment.

<img width="1358" alt="Screen Shot 2023-08-09 at 1 39 05 PM" src="https://github.com/omni-us/jsonargparse/assets/11243913/0ddc71f0-adda-486b-8551-cf700fd71209">

How can I get rid of the args: `--config` and `--print_config`?, in other I'd like to keep `name` and `--prize` when I execute `--help` 

Thanks,
Giuliano.
PS, Just in case, this is from macOS

**Comment by mauvilsa** [comment]
> I am trying to reproduce the example in https://jsonargparse.readthedocs.io/en/v4.23.1/#basic-usage

Regarding the docstrings, you can see below the example a note about reproducing.

> How can I get rid of the args: --config and --print_config?

There is no option to remove them. `jsonargparse.CLI` is not intended to provide 100% control, but only a minimal boilerplate way to implement a CLI. Also note that in the example, the output is not intended to be the complete output. You can see `...` meaning that part was omitted. The point of the example is to show that both options `name` and `prize` are automatically added.

If you want full control of the parser, then create the parser yourself. The example would become:

```python
from jsonargparse import ArgumentParser

def command(name: str, prize: int = 100):
    """Prints the prize won by a person.

    Args:
        name: Name of winner.
        prize: Amount won.
    """
    print(f"{name} won {prize}€!")

def cli():
    parser = ArgumentParser()
    parser.add_function_arguments(command, as_group=True, as_positional=True)
    cfg = parser.parse_args()
    command(**cfg)

if __name__ == "__main__":
    cli()
```

And the help would be:

```shell
$ python example.py -h
usage: example.py [-h] [--prize PRIZE] name

options:
  -h, --help     Show this help message and exit.

Prints the prize won by a person:
  name           Name of winner. (required, type: str)
  --prize PRIZE  Amount won. (type: int, default: 100)
```
