### ISSUE TITLE
make --some_arg required 

### ISSUE THREAD

**Issue by gmaggi** [omni-us/jsonargparse#350]
Hi,

In `def command(name: str, prize: int = 100):` name is required, while prize has a default value and is optional. So, to my understanding, `prize` has to be passed with `--` and `name` not.

How can I pass a required arg with `--` in front?. 

Thanks!

**Comment by mauvilsa** [comment]
With `jsonargparse.CLI` you can use the option `as_positional=False`. Adding an argument to a parser would be `parser.add_argument("--name", type=str, required=True)`.
