### ISSUE TITLE
Dataclass as CLI function argument

### ISSUE THREAD

**Issue by carmocca** [omni-us/jsonargparse#36]
Hello again!

Is this supported by the CLI?

```python
from dataclasses import dataclass
from jsonargparse import CLI

@dataclass
class MySQLConfig:
    host: str = "localhost"
    port: int = 3306

def my_app(cfg: MySQLConfig) -> None:
    print(f"{cfg.host}, {cfg.port}")

if __name__ == "__main__":
    CLI(my_app)
```

where `python file.py` would print `localhost, 3306` and you could do something like `python file.py --cfg.host="test"` and it would print `test, 3307`

Thanks!

**Comment by mauvilsa** [comment]
This is not supported. A class used as a type hint means that the argument accepts an instance of this class or any subclass. So it would work with `class_path` and `init_args` as explained in https://omni-us.github.io/jsonargparse/#class-type-and-sub-classes.
