### ISSUE TITLE
How to properly capture a parser and manually add a sub-parser on top?

### ISSUE THREAD

**Issue by bilelomrani1** [omni-us/jsonargparse#360]
Hi, I am trying to manipulate a parser automatically built by `CLI` to manually add a subparser to it without modifying the original object. For instance, consider the following:

```python
from dataclasses import dataclass

from jsonargparse import CLI, capture_parser


@dataclass
class Config:
    a: int
    b: float


class MyObject:
    def __init__(self, option: int) -> None:
        self.option = option


if __name__ == "__main__":
    parser = capture_parser(CLI(Config))
    parser.add_class_arguments(MyObject, "obj")
    config = parser.parse_args()
    print(config)

```

I want to add a subparser for the `MyObject` class on top of the parser auto-generated by `CLI(Config)`, but this does not work as expected: when calling `python main.py --help` I get

```console
usage: test.py [-h] [--config CONFIG] [--print_config[=flags]] a b

Config(a: int, b: float)

positional arguments:
  a                     (required, type: int)
  b                     (required, type: float)

options:
  -h, --help            Show this help message and exit.
  --config CONFIG       Path to a configuration file.
  --print_config[=flags]
                        Print the configuration after applying all other arguments and exit. The optional flags
                        customizes the output and are one or more keywords separated by comma. The supported flags are:
                        comments, skip_default, skip_null.
```

hence the `obj` subparser is not properly added. I am wondering what is the proper way for this use case. Perhaps I misunderstand how to use `capture_parser`. I spent some time trying to come up with a solution using `CLI(Config, return_parser=True)` but this flag is deprecated so I wonder what is the proper way of doing it. Thank you for your help.

**Comment by mauvilsa** [comment]
You have a mistake in the code. `capture_parser` expects a **function** that when executed, creates a parser and calls `parse_args`. `CLI(Config)` does not return a function. In fact, when you give `--help`, the call to `capture_parser` is not even being run. `CLI(Config)` is printing its help and then exiting. A correct way to capture the parser could be:

```python
parser = capture_parser(lambda: CLI(Config))
```

**Comment by bilelomrani1** [comment]
Thank you for the clarification, I missed this info, this seems to do what I expected. 

To give a little more background on my use case, I have a class that takes file paths in its constructor (among other things). I want to automatically build an argument parser using `CLI` for it and then patch the argument corresponding to the paths to add a `Path_fr` validator on top.  The object can be used independently from the CLI, in an existing library, so I cannot modify it too much, I am building a CLI application on top of it. Ideally, I want to keep the CLI logic and the "business" logic separated.

So my question is: once the parser is captured, what is the recommended way to add a validator to an existing argument? I really like the parser auto-generated by `CLI` but I want slightly more control

**Comment by mauvilsa** [comment]
Modifying arguments already added to a parser is not something that `argparse` provides. How about:

```python
import os
from dataclasses import dataclass

from jsonargparse import CLI
from jsonargparse.typing import Path_fr

@dataclass
class Config:  # This class would be imported from the third party library instead of defined here
    p1: str
    p2: float

@dataclass
class Config2(Config):
    def __init__(self, p1: Path_fr, **kw) -> None:
        super().__init__(p1=os.fspath(p1), **kw)

if __name__ == "__main__":
    CLI(Config2)
```

**Comment by bilelomrani1** [comment]
Thank you very much, sounds good, that definitely helps!
