### ISSUE TITLE
class instantiation with multiple parameters

### ISSUE THREAD

**Issue by hadipash** [omni-us/jsonargparse#372]
Hello, I have a question on how I can instantiate a class that requires multiple parameters that determined during run time only?
I followed the example on [Optimizer](https://jsonargparse.readthedocs.io/en/v4.24.0/#callable-type) but can't figure out how I can expand it to multiple parameters:

```python
# Example from the website
class Optimizer:
    def __init__(self, params: Iterable):
        self.params = params


class SGD(Optimizer):
    def __init__(self, params: Iterable, lr: float):
        super().__init__(params)
        self.lr = lr


if __name__ == '__main__':
    value = {
        "class_path": "SGD",
        "init_args": {
            "lr": 0.01,
        },
    }

    parser = ArgumentParser()
    parser.add_argument("--optimizer", type=Callable[[Iterable], Optimizer])
    cfg = parser.parse_args(["--optimizer", str(value)])
    init = parser.instantiate_classes(cfg)
    optimizer = init.optimizer([1, 2, 3])
```

Let's say I want to add one more parameter to `SGD(params, weight, lr)`. How will the flow change?

```python
class SGD(Optimizer):
    def __init__(self, params: Iterable, weight: float, lr: float):
...
parser.add_argument("--optimizer", type=Callable[[Iterable, float], Optimizer])
```
gives the following error:
```
usage: example.py [-h] [--optimizer OPTIMIZER]
example.py: error: Parser key "optimizer":
  Expected a dot import path string: SGD
```
Setting `class_path` to `__main__.SGD` produces another error:
```
usage: example.py [-h] [--optimizer OPTIMIZER]
example.py: error: Parser key "optimizer":
  Type typing.Callable[[typing.Iterable, float], __main__.Optimizer] expects a function or a callable class: Expected '__main__.SGD' to be a class that instantiates into callable or a subclass of False.. Got value: Namespace(class_path='__main__.SGD', init_args=Namespace(lr=0.01))

```

**Comment by mauvilsa** [comment]
Thank you for reporting!

This seems to be a bug in line:
https://github.com/omni-us/jsonargparse/blob/826d7863ab34654af0d73d8f42fb5768ce64f5f3/jsonargparse/_typehints.py#L891

Should be instead `return_type = typehint.__args__[-1]`.

**Comment by mauvilsa** [comment]
@hadipash would you be interested in contributing the fix?

**Comment by hadipash** [comment]
Interested, but can only start working on this issue in the middle of next week at the earliest, if it's ok.

**Comment by mauvilsa** [comment]
> can only start working on this issue in the middle of next week at the earliest, if it's ok.

That is okay. The task should be simple. Possibly just that line that I referenced above and add a unit test.
