### ISSUE TITLE
`CLI` uses incorrect argument types when arguments have `Annotated` type.

### ISSUE THREAD

**Issue by rusmux** [omni-us/jsonargparse#384]
## 🐛 Bug report

`CLI` uses incorrect argument types when arguments have `Annotated` type.

### To reproduce

```Python
from jsonargparse import CLI
from pydantic import Field
from typing_extensions import Annotated

NormalizedFloat = Annotated[float, Field(ge=0, le=1)]


def print_float(value: float) -> None:
    print(value, type(value))


def print_normalized_float(value: NormalizedFloat) -> None:
    print(value, type(value))


if __name__ == '__main__':
    CLI([print_float, print_normalized_float])
```

```Bash
python -m main print_float 0.1
0.1 <class 'float'>
python -m main print_normalized_float 0.1
0.1 <class 'str'>
```

### Expected behavior

```Bash
python -m main print_normalized_float 0.1
0.1 <class 'float'>
```

### Environment

- jsonargparse version (e.g., 4.8.0): 4.24.1
- Python version (e.g., 3.9): 3.10.12
- How jsonargparse was installed (e.g. `pip install jsonargparse[all]`): pip install jsonargparse[all]
- OS (e.g., Linux): macOS 13.5.2

**Comment by mauvilsa** [comment]
Thank you for reporting! Support for `Annotated` hasn't yet been added, see [type-hints](https://jsonargparse.readthedocs.io/en/v4.24.1/#type-hints). So technically this is a new feature instead of a bug.
