### ISSUE TITLE
Changing env variable format

### ISSUE THREAD

**Issue by RoelantStegmann** [omni-us/jsonargparse#39]
I wonder if it's possible to change the `[PREFIX_][LEV__]*OPT` format, e.g. specify the environment variable on the argument explicitely? I prefer to do this explicitely for users who are not aware of the convention. 

And maybe we can add something in the docs for when you don't want to use PREFIX or LEV

And can you overwrite the entire class with a dictionary? 

Sorry for the messy issue with the many questions :D If you explain I can make a PR for the README ;)

**Comment by mauvilsa** [comment]
> I wonder if it's possible to change the `[PREFIX_][LEV__]*OPT` format, e.g. specify the environment variable on the argument explicitely? I prefer to do this explicitely for users who are not aware of the convention.

jsonargparse is mostly intended to make simple the definition of large complex parsers with many options. Being able to specify the environment variable name for a single argument does not bring much value in this case. Furthermore, adding this feature inevitably adds significant complexity that can be a burden to maintain. I don't doubt that this could be useful in some cases, but unless there is a truly significant number of people asking for it, I will not consider it for implementation. So don't expect this any time soon.

If your only concern is users not being aware of the convention, this is something that can be clarified and if needed improved on the sort term. It is generally expected that users look at the documentation to learn how to use a command line tool. With jsonargparse the `--help` is always available for this purpose. When parsing of environment variables is enabled by default, i.e. instantiate `ArgumentParser` with `default_env=True`, the help shows for every argument which is the corresponding environment variable name that should be used. No need to remember some convention. Additionally the help of command line tools could be included in the documentation of a package. With jsonargparse this can be done with Sphinx and the sphinx-argparse extension.

**Comment by mauvilsa** [comment]
@RoelantStegmann did this help?

**Comment by RoelantStegmann** [comment]
It did a bit! I ended up using the package for one project, to get a feel and play around. In the end I think I quite liked most of it. It would be better if the help showed the ENV. (I used it in lambda's and containers which are often mainly controlled by env variables), but it works as well with the lines of comments I added now. 

My last concern was that the yaml defaults cannot contain more information than the argparser, when I was trying to sneak in some other parameters that don't need to be exposed on the command line but I would put in a normal settings file. (And you cannot make them part of the argparser if they are for example a list of flexible key-value pairs). So was doubting a bit there. 

Anyway, thanks for thinking along.

**Comment by mauvilsa** [comment]
> It would be better if the help showed the ENV.

As I mentioned in my previous comment, the environment variable names are shown in the help if you instantiate `ArgumentParser` with `default_env=True`.

> My last concern was that the yaml defaults cannot contain more information than the argparser, when I was trying to sneak in some other parameters that don't need to be exposed on the command line but I would put in a normal settings file. (And you cannot make them part of the argparser if they are for example a list of flexible key-value pairs).

I am not sure if I understand what you mean. Maybe give an example to make it easier to know what you need. It is possible to add an argument that is not shown in the help and accepts any amount of key value pairs. It is just doing for example`parser.add_argument('--aux', help=SUPPRESS, action=ActionJsonSchema(schema={'type': 'object'}))`.
