### ISSUE TITLE
[FR]: Add type Path_dcr to accept directories that could be created if mkdir(parents=True)

### ISSUE THREAD

**Issue by noamsgl** [omni-us/jsonargparse#393]
Hi, great project. Thanks.

## Main issue
The suggested way to type check for creatable directories is done like this:
```python
from jsonargparse.typing import Path_dc

def foo(fp: Path_dc):
   ...
  fp.mkdir(parents=True)


CLI(foo)
```

However, when trying to instantiate `/home/bar/baz` while `/home/bar` does not exist, we get the error: 
```
Not of type Path_dc: Directory is not creatable since parent directory does not exist: '/home/bar/baz'
```

However, in my application, I am creating the path using `parents=True`. In this particular use case, it is a creatable directory, and yet the type checker throws an error.

## Possible alternative
Add another type like `Path_dcr` which is a directory, creatable recursively, for which the type checker checks if the directory could be created if `parents=True` were set.

**Comment by mauvilsa** [comment]
This is already possible, though somewhat difficult to find in the docs. It is only mentioned in the description of [`jsonargparse.Path`](https://jsonargparse.readthedocs.io/en/v4.25.0/#jsonargparse.Path). The way to do it is:

```python
from jsonargparse.typing import path_type

Path_dcc = path_type("dcc")

def foo(fp: Path_dcc):
   ...
   fp.mkdir(parents=True)

CLI(foo)
```

**Comment by noamsgl** [comment]
Works! Thanks.
