### ISSUE TITLE
Dump relative paths with respect to the config save-location, instead of current working directory. 

### ISSUE THREAD

**Issue by didirus** [omni-us/jsonargparse#4]
- This is because when you want to use the saved config for a next program execution, the relative paths will be w.r.t. the config location. There currently is a mismatch in paths between dump() and config load. 
- This requires dump() to take a path as argument, which it does not at the moment.

**Comment by mauvilsa** [comment]
@didirus even though the current description of this feature request gives some idea of what is its intention, it would be good if you could elaborate a bit more. In particular it would be great if you give an example, with some original config in some location and referencing relative paths, and then a new location of where the config would be saved and how its contents would look like if this feature were implemented. This will help in assessing how viable this feature is, technical problems it might have and if maybe it would conflict with other behaviors that might be wanted.
