### ISSUE TITLE
Option to show full help message with ActionParser arguments. 

### ISSUE THREAD

**Issue by stasbel** [omni-us/jsonargparse#41]
I actively am using subparsers with `jsonargparse.ActionParser`. The problem is -- arguments for subparser's nodes don't appear in main parser help message.
I know it's outlined in README, but It's very confusing to see half of arguments available with`script.py --help`.

**Comment by mauvilsa** [comment]
I agree it would be much nicer if the ActionParser arguments are shown in the main parser help. Though I am not sure how difficult it would be to implement this. Will take a look at it later.

**Comment by mauvilsa** [comment]
This is now part of release v3.7.0.
