### ISSUE TITLE
Convert config file to corresponding CLI command

### ISSUE THREAD

**Issue by EthanMarx** [omni-us/jsonargparse#426]
## 🚀 Feature request
Ability to convert a config file to the corresponding CLI command.

### Motivation
Useful in instances where jobs are launched remotely (e.g. kubernetes) and the config doesn't necessarily live on the remote machine.

(this may already exist, although I couldn't find exactly where this would be done) Thank!

**Comment by EthanMarx** [comment]
Thanks for getting back. As a minimal example consider this config file from the docs

```yaml
# File: example.yaml
lev1:
  opt1: from yaml 1
  opt2: from yaml 2
```

and this command that is parsed

```python
parser.add_argument("--lev1.opt1", default="from default 1")  
parser.add_argument("--lev1.opt2", default="from default 2")  
parser.add_argument("--config", action=ActionConfigFile)  
cfg = parser.parse_args(["--lev1.opt1", "from arg 1", "--config", "example.yaml", "--lev1.opt2", "from arg 2"])
```

I wan't to be able to construct the equivalent cli command that does not reference the config. In this example, lev1.opt1 gets overwritten by the config, and lev1.opt2 is parsed directly from the command line, so the corresponding command would be:

```
--lev1.opt1 "from yaml 1" --lev1.opt2 "from arg 2"
```

**Comment by mauvilsa** [comment]
You don't need to convert the command. Given that the motivation mentions kubernetes, I can suggest multiple ways providing configuration.

- Set the entire config (raw yaml/json content) to a single environment variable, and then run the command as:
  ```
  cli.py --config "$RAW_YAML_CONFIG"
  ```
- Enable [environment variable](https://jsonargparse.readthedocs.io/en/v4.27.1/#environment-variables) parsing, and use the specific environment variable names for your CLI. For example, if the parser is created like `ArgumentParser(env_prefix="APP", default_env=True)` and has an `ActionConfigFile` like the example above, the config environment variable name would be `APP_CONFIG`. So you can set that environment variable (raw yaml/json content) and run the command without any arguments.
- Without changing the source code (i.e. add `default_env=True`) you can enable environment variable parsing by setting `JSONARGPARSE_DEFAULT_ENV=true`. You can see the names of the environment variables of your CLI by running `JSONARGPARSE_DEFAULT_ENV=true cli.py --help`.
- Like mentioned in my first comment, give as config a path to remote location. For example for a file in an s3 bucket, the command could be run like:
  ```
   cli.py --config s3://yourbucket/config.yaml
  ```
  or set the remote path to an environment variable and run as
  ```
   cli.py --config "$REMOTE_PATH_TO_CONFIG"
  ```

**Comment by EthanMarx** [comment]
thank you for the suggestions was not aware of these features! Will close this out then
