### ISSUE TITLE
CLI fails with `torch.dtype` arguments

### ISSUE THREAD

**Issue by ioangatop** [omni-us/jsonargparse#446]
## 🐛 Bug report

The CLI seems to not be able to handle `torch.dtype` arguments; pretty important for torchvision [ToDtype](https://pytorch.org/vision/main/generated/torchvision.transforms.v2.ToDtype.html?highlight=todtype#torchvision.transforms.v2.ToDtype) transform.

### To reproduce

Using the CLI:

```python
# main.py
import torch
from jsonargparse import CLI


def interface(dtype: torch.dtype) -> None:
    print(f"dtype: {dtype} ({type(dtype)})")

CLI(interface)
```

Run with:
```sh
python3 main.py torch.float32
```

### Expected behaviour: 

The above to print:
```
dtype: torch.float32 (<class 'torch.dtype'>)
```
### Environment

- jsonargparse version (e.g., 4.8.0):
- Python version (e.g., 3.9):
- How jsonargparse was installed (e.g. `pip install jsonargparse[all]`):
- OS (e.g., Linux):

**Comment by mauvilsa** [comment]
Thank you for repointing! This should be fixed with the pull request that was just merged.
