### ISSUE TITLE
Read the standard input and write in the standard output

### ISSUE THREAD

**Issue by mquillot** [omni-us/jsonargparse#463]
## 🚀 Feature request

Permits to specify standard input with Path_fr

### Motivation

Sometimes, I would like to be able to create a full pipeline of commands which communicate through the standard input and output. But I would also like that run each command with input file instead of standard input. (same for output)

### Pitch
jsonargparse don't permits it today with Path_fr. (or I didn't find the feature?)
For instance, if I put "-" (common practice for specifying standard input) with the corresponding option, it will answer that the file does not exist.

Here an example of code:
```
parser = ArgumentParser()

parser.add_argument(
    "--input-file",
    dest="input_file",
    type=Path_fr,
    default="-",
    help="Path of input file (standard input if - specified)",
)
```

The command I run:
`python -m my_command --input-file -`

And the error I receive:
`Not of type Path_fr: File does not exist: /folderA/folderB/-`

But, in this situation, I would like that the program does not check the existence of the file as I would like to read the standard input.

It could be great to have the same feature for the output also.

### Alternatives

I tested also to use the FileType of argparse as a type, but jsonargparse does not accept it.
```
from argparse import FileType

parser.add_argument(
    "--input-file",
    dest="input_file",
    type=FileType("r"),
    default="-",
    help="Path of input file (standard input if - specified)",
)
```
Error:
`error: Validation failed: Parser key "input_file": expected str, bytes or os.PathLike object, not _io.TextIOWrapper`

**Comment by mquillot** [comment]
I think in the following file : 
https://github.com/omni-us/jsonargparse/blob/main/jsonargparse/_util.py

You can just change class Path to accept "-" as a possible value skipping the check.
You can also add a mode that path_type will transmit. The mode could be specified with the character "-" specifying that we accept standard input or output. For instance, you could have the following code:

```python

        elif isinstance(path, (str, os.PathLike)):
            if "-" in mode and path == "-":
               # Do something here...
               # add a flag?
               self._skip_check = True
            else:
              path = os.fspath(path)
              cwd = os.fspath(cwd) if cwd else None
              abs_path = os.path.expanduser(path)
              if self._file_scheme.match(abs_path):
                  ...

```

What do you think?

**Comment by mauvilsa** [comment]
There is no need for a new mode. Also don't set _skip_check to true since that has other consequences. Just the [`if "r" in mode ...`](https://github.com/omni-us/jsonargparse/blob/eb40256137d1689de82d4c3b2346eb79d4ff6486/jsonargparse/_util.py#L560) should not raise TypeError when the value is dash. The same for "w". Also [get_content](https://github.com/omni-us/jsonargparse/blob/eb40256137d1689de82d4c3b2346eb79d4ff6486/jsonargparse/_util.py#L636) should support reading from stdin. And finally, there should be new unit tests to cover all of this.

**Comment by mauvilsa** [comment]
@mquillot are you interested in contributing this feature? Just asking to not work on this. Otherwise, I might implement this soon.

**Comment by mauvilsa** [comment]
> I am interested in implementing it but maybe I could use a little help.

Certainly, I can help. Steps would be:
- For the repo
- Locally clone your fork
- Create a branch for the feature
- Develop and push the changes
- Create a pull request from your branch to jsonargparse/main

Also before developing, be sure to have a read of https://github.com/omni-us/jsonargparse/blob/main/CONTRIBUTING.rst

**Comment by mquillot** [comment]
It was a little bit complicated to avoid conflict with the following feature: giving "-" to specify that a list of files is given as input. So, I proposed a solution. I hope it will be ok for you.

You will find my PR here: https://github.com/omni-us/jsonargparse/pull/475
