### ISSUE TITLE
Not able to mimic the behavior of argparse

### ISSUE THREAD

**Issue by jongharyu** [omni-us/jsonargparse#5]
I am playing with this library for my project, but encountering some issue with a basic behavior with `type` specification in `add_argument`.

While the following snippet 
```python3
import argparse
this = argparse.ArgumentParser()
this.add_argument('--ints', nargs='+', type=int)
this.parse_args(args=['--ints', '3', '4', '5'])
```
gives `Namespace(ints=[3, 4, 5])`, the same snippet with `jsonargparse`, i.e.,
```python3
import jsonargparse
that = jsonargparse.ArgumentParser()
that.add_argument('--ints', nargs='+', type=int)
that.parse_args(args=['--ints', '3', '4', '5'])
```
raises an error: `jsonargparse.ParserError: Parser key "temp": int() argument must be a string, a bytes-like object or a number, not 'list'`. I believe this is not an expected behavior. 

I took a quick look at `parse_args` implementation and found that it raises the error because the type conversion is done by calling `parse_args` of `argparse` in `cfg = super().parse_args(args=args, namespace=namespace)`, while it tries to invoke actions again afterwards later in `self.check_config(cfg_ns, skip_none=True)`.

Am I missing something? Otherwise, it would be great if this can be resolved :)

**Comment by mauvilsa** [comment]
@jongharyu thank you very much for reporting this. I have now committed a new version (https://github.com/omni-us/jsonargparse/releases/tag/v2.13.0) that fixes this and added unit tests to prevent a regression. Please check that it works as expected.

**Comment by jongharyu** [comment]
Thanks a lot for your prompt response. I just checked that it works now!
