### ISSUE TITLE
the issue about setup.py

### ISSUE THREAD

**Issue by dedean** [omni-us/jsonargparse#500]
![image](https://github.com/omni-us/jsonargparse/assets/100350813/d350d6c2-00fc-423c-a145-273ae546a6b1)
 how to setup

**Comment by mauvilsa** [comment]
Any particular reason why you are using such an old version of jsonargparse? The latest versions don't even have a `setup.py` file. The repo now follows the new [PEP 621](https://peps.python.org/pep-0621/) standard, using a `pyproject.toml` file.

It is not clear exactly what you want to do. For using the package the recommended way is to `pip install ...`. Setting up for development is explained in [CONTRIBUTING.rst](https://github.com/omni-us/jsonargparse/blob/main/CONTRIBUTING.rst).

**Comment by dedean** [comment]
Sorry to bother you, but due to conditions, I can only download the offline package for installation. What command should I execute to install if I download the latest package



发自我的iPhone


------------------ Original ------------------
From: Mauricio Villegas ***@***.***&gt;
Date: Fri,May 17,2024 9:38 PM
To: omni-us/jsonargparse ***@***.***&gt;
Cc: dedean ***@***.***&gt;, Author ***@***.***&gt;
Subject: Re: [omni-us/jsonargparse] the issue about setup.py (Issue #500)

**Comment by mauvilsa** [comment]
From source the package can be installed like
```
pip install .
```
If you want optional dependencies, then you can do for example
```
pip install ".[signatures]"
```

**Comment by dedean** [comment]
Do you mean that I enter the downloaded jsonargprase offline package and directly execute the pip list? (My server cannot connect to the network)

发自我的iPhone


------------------ Original ------------------
From: Mauricio Villegas ***@***.***&gt;
Date: Fri,May 17,2024 11:31 PM
To: omni-us/jsonargparse ***@***.***&gt;
Cc: dedean ***@***.***&gt;, Author ***@***.***&gt;
Subject: Re: [omni-us/jsonargparse] the issue about setup.py (Issue #500)





 
From source the package can be installed like
 pip install .  
If you want optional dependencies, then you can do for example
 pip install ".[signatures]"

**Comment by mauvilsa** [comment]
For example, for the latest version you can (linux/mac):
```
virtualenv -p python3 venv
source venv/bin/activate
wget https://files.pythonhosted.org/packages/19/ee/84ddf56631ae11c7751a1e5ab543803c6c8f7857d41f91ee01b1b886f0eb/jsonargparse-4.28.0.tar.gz
tar xzf jsonargparse-4.28.0.tar.gz
cd jsonargparse-4.28.0
pip install .
```

But, if pip does not get access to the internet, the install will fail trying to fetch dependencies. The only required dependency is pyyaml, so you would have to download and manually install that one beforehand. If you want more optional dependencies, then you would need to install each of them manually.

**Comment by dedean** [comment]
ok i will try this method tomorrow .Thank you



发自我的iPhone


------------------ Original ------------------
From: Mauricio Villegas ***@***.***&gt;
Date: Fri,May 17,2024 11:51 PM
To: omni-us/jsonargparse ***@***.***&gt;
Cc: dedean ***@***.***&gt;, Author ***@***.***&gt;
Subject: Re: [omni-us/jsonargparse] the issue about setup.py (Issue #500)

**Comment by mauvilsa** [comment]
Hopefully this helped! Closing.
