### ISSUE TITLE
Shtab complete: the action.complete of Classes, methods and functions should be `shtab.FILE`

### ISSUE THREAD

**Issue by tshu-w** [omni-us/jsonargparse#556]
## 🐛 Bug report

Currently, the `action.complete` for `shtab` is `FILE` only when it is `ActionConfigFile` or `Pathlike` for `ActionTypeHint`, however, these doesn't cover the action of `_ActionConfigLoad`.

https://github.com/omni-us/jsonargparse/blob/f5f24221ff6d44f97310e72d808b748da1d30978/jsonargparse/_completions.py#L144-L162

#### Simple Example

```python
# cli.py
from jsonargparse import ArgumentParser
from calendar import Calendar

class MyClass:
     def __init__(self, calendar: Calendar):
         self.calendar = calendar

parser = ArgumentParser()
parser.add_class_arguments(MyClass, "myclass", sub_configs=True)
cfg = parser.parse_args()
```

```console
λ python cli.py --print_shtab=zsh
...
"--myclass[Path to a configuration file.]:myclass:"
...
```
Expected:
```console
λ python cli.py --print_shtab=zsh
...
"--myclass[Path to a configuration file.]:myclass:_files"
...
```
since the following command work:
```console
python cli.py --myclass test.yaml
```

with `test.yaml`:
```yaml
calendar:
  class_path: calendar.Calendar
  init_args:
    firstweekday: 1
```

### Environment

- jsonargparse version: 4.32.0
- Python version: 3.12
- How jsonargparse was installed: pip
- OS: Ubuntu 22.04

**Comment by mauvilsa** [comment]
Thank you for reporting. This should be easy to fix.
