### ISSUE TITLE
Correct way of selecting between classes/subclasses

### ISSUE THREAD

**Issue by MiguelMonteiro** [omni-us/jsonargparse#565]
I am attempting to move the configuration of my deep learning code from `simple-parsing` to `jsonargparse`, I have read the documentation but cannot figure out what is the canonical way of selecting between different possible classes. For example, say I want to select my optimizer type and the configure it. The following code does not work but gives an idea of what I am trying to achieve.

```
from jsonargparse import ArgumentParser
from torch.optim import SGD, Adam, AdamW, Optimizer

if __name__ == "__main__":
    parser = ArgumentParser(description="Example CLI")
    parser.add_class_arguments(SGD | Adam | AdamW, nested_key="optimizer", skip=["params"])
    args = parser.parse_args()
    cfg = args.config
    
  ```
   
I understand that I could potentially use `parser.add_class_arguments(Optimizer)` which would create configuration for all known subclasses of optimizers. This is not desirable since, while for optimizers this would be fine, for something like `nn.Module` it would expose all known torch modules.

**Comment by MiguelMonteiro** [comment]
Thank you. For the callable type option is there a way of passing strings, e.g. `sgd`, `adamw` instead of the class path, e.g. `torch.optim.SGD`, `torch.optim.AdamW`? 

Additionally, is there a way of showing the help string for a particular optimizer after the selection. Say `program.py --optimizer=torch.optim.SGD --help` would give the docstring and parameter descriptions provided in torch?

**Comment by mauvilsa** [comment]
> Thank you. For the callable type option is there a way of passing strings, e.g. `sgd`, `adamw` instead of the class path, e.g. `torch.optim.SGD`, `torch.optim.AdamW`?

Yes, instead of giving a full class path you can do
```
program.py --optimizer=SGD --optimizer.lr=0.001 ...
```

> Additionally, is there a way of showing the help string for a particular optimizer after the selection. Say `program.py --optimizer=torch.optim.SGD --help` would give the docstring and parameter descriptions provided in torch?

For subclasses the help is printed like
```
program.py --optimizer.help SGD
```
Though, from what I see this is not yet implemented for the callable type.

**Comment by MiguelMonteiro** [comment]
Thank you for your help
