### ISSUE TITLE
Parsing `TYPE_CHECKING` guarded import doesn't work in combination with `Type`

### ISSUE THREAD

**Issue by EthanMarx** [omni-us/jsonargparse#572]
## 🐛 Bug report

When using the `Type` annotation in conjunction with a `TYPE_CHECKING` guarded import, e.g.

```python
from typing import Type, TYPE_CHECKING
from jsonargparse import ArgumentParser

if TYPE_CHECKING:
    from pytorch.lightning.cli import LightningCLI

def dummy(cli_cls: Type["LightningCLI"]):
    print(cli_cls)


def main():
    parser = ArgumentParser()
    parser.add_function_arguments(dummy)
    args = parser.parse_args()
```
I get the following error

```console
ValueError: With fail_untyped=True, all mandatory parameters must have a supported type. Parameter 'cli_cls' from '__main__.test' does not specify a type.
```

Although, this parser set up works when removing the `TYPE_CHECKING` guarded import, and importing directly

### Environment

- jsonargparse version: 4.3.1
- Python version: 3.9 
- How jsonargparse was installed: poetry
- OS: linux

**Comment by mauvilsa** [comment]
Thank you for reporting! Would you be interested in contributing the fix?

**Comment by EthanMarx** [comment]
Sure - would you be able to point me in the right direction?

**Comment by mauvilsa** [comment]
Certainly.

1. Setup a local environment as explained in [CONTRIBUTING.rst#development-environment](https://github.com/omni-us/jsonargparse/blob/main/CONTRIBUTING.rst#development-environment).
2. The tests related to `TYPE_CHECKING` are in `jsonargparse_tests/test_postponed_annotations.py`, so make sure those tests run, like
    ```
    pytest -v jsonargparse_tests/test_postponed_annotations.py
    ```
3. Have a look at the existing tests: [test_postponed_annotations.py#L192-L294](https://github.com/omni-us/jsonargparse/blob/1bab38ae7a5fe281c62fe784fc620bbbf259f2e8/jsonargparse_tests/test_postponed_annotations.py#L192-L294)
4. Maybe, debug through one of the tests to get a bit of understanding of how things work.
5. Before trying to fix, extend `test_postponed_annotations.py` to include a test for this case which is failing. That is, add an entry in the `if TYPE_CHECKING:` block and implement a `test_*` function that fails as you have observed with the current version of the code.

The unit test would already be a valuable contribution. The following step would be to understand what is currently happening and figure out where to fix/improve the code. This feature makes use of AST parsing, so it might not be trivial to understand and fix. But you can give it a shot. If it seems to complex just ask again, or I could continue from where you left off.

**Comment by EthanMarx** [comment]
Thank you! I actually think I found a solution. I have a PR with unit tests ready to go, but can't get past the `pre-push` testing hooks, I think due to #574

**Comment by mauvilsa** [comment]
You can do `git push --no-verify`.
