### ISSUE TITLE
Multiple `default_config_files` default values

### ISSUE THREAD

**Issue by stasbel** [omni-us/jsonargparse#58]
Say, I want to set defaults from two config files with keys intersection.
I expect it to set defaults with each next config in the list override previous values.
But instead, it says:
```
default config file locations:
  ['config1.yaml', 'config2.yaml'], Note:
  default values below will be ones overridden by the contents of:
  config1.yaml
```
Which completely ignores information from config2.yaml.
Why is it expected behavior and could it be fixed?
Thanks.

**Comment by mauvilsa** [comment]
It is like this just because it hasn't been implemented. Surely it could be implemented.

**Comment by stasbel** [comment]
hi, any progress on this?

**Comment by mauvilsa** [comment]
Sorry @stasbel I haven't worked on this. Currently there are other higher priority tasks in jsonargparse. You will have to wait a bit for me to have time for it.

**Comment by mauvilsa** [comment]
This is now part of release v3.16.0.
