### ISSUE TITLE
Empty tuple default value not supported

### ISSUE THREAD

**Issue by MiguelMonteiro** [omni-us/jsonargparse#589]
## 🐛 Bug report

Empty tuples are not supported by the parser.

### To reproduce

```
from dataclasses import dataclass

from jsonargparse import ArgumentParser


@dataclass
class TestCfg:
    a: tuple[int, ...] = ()


if __name__ == "__main__":
    parser = ArgumentParser(description="CLI for training models", exit_on_error=False)
    parser.add_argument("test", type=TestCfg)
    args = parser.parse_args()
    print(args)
```
Running the following program without passing any arguments or by passing an empty list/tuple `"[]"` results in the following error:
```
argparse.ArgumentError: Validation failed: Parser key "test.a":
  Expected a non-empty tuple. Got value: []
  ```

### Expected behavior

To be able to parse empty tuples without errors.

### Environment

- jsonargparse version: 4.33.1
- Python version: 3.10
- How jsonargparse was installed: pip
- OS: MacOS

**Comment by mauvilsa** [comment]
Thank you for reporting!

This looks like an easy fix. Just adding a unit test and extending this `if` condition https://github.com/omni-us/jsonargparse/blob/a8b8b151ab26db57cae94c6f5de9c618daf4971b/jsonargparse/_typehints.py#L850

@MiguelMonteiro would you like to contribute de fix?

**Comment by MiguelMonteiro** [comment]
Hi @mauvilsa I am happy to contribute, I will open a PR when I get the time.
