### ISSUE TITLE
Help mode should skip all validation in the default config

### ISSUE THREAD

**Issue by alexpolozov** [omni-us/jsonargparse#60]
When `--help` is requested, any validation of the default config file should be skipped. #48 implements one instance of it, but it's not the only issue that could arise and break help display. For example:
``` py
parser.add_argument("-d", "--data-path", type=path_type('dr'), help="Path to the data directory")
```
```
$  python main.py --help
Parser key "data_path": Directory does not exist: C:\Path\That\Does\Not\Exist
usage: main.py [-h] ...
main.py: error: Parser key "data_path": Directory does not exist: C:\Path\That\Does\Not\Exist
```
There are probably other examples of smart type validation that are great in jsonargparse in general, but could break help display when run on a default config file.

**Comment by mauvilsa** [comment]
In general I agree. However, from what I remember the last time I modified this part of the code there is no easy way to do this. There is no clear decoupling of validation and other features that are necessary to get the defaults that will be used. This is related to jsonargparse being an extension of argparse and how it is based on action classes.

I will look at it again. I doubt that this can be fixed in general. But at least I will try to do something related to the paths which clearly is a problem.

**Comment by mauvilsa** [comment]
@alexpolozov I have pushed a fix which makes sure that `--help` still works when a default config contains invalid data. In this case the help will not show the values overridden by the `default_config_files` but it will say that the default config is invalid and what the error is.

I analyzed again your description and now I don't agree. The data in `default_config_files` should always be valid and the validation should not be disabled. I think in your `--data-path` example either the data path should exist or the default config file should not include a value for `data_path`. The `default_config_files` are intended for a config that is installed with the program or in the user's home directory to customize these defaults. If it comes from a program install, then the installation should also install the data and the default point to the correct location. If the user overrides this default it should point the new existing location of the data. If the data is not supposed to be part of an install, then it means that it should be an input when the program is run. If your case is neither of these, then I don't see why the type should be `path_type('dr')`.

**Comment by alexpolozov** [comment]
@mauvilsa First, thank you for the fix!
Second, I think there are arguments for both perspectives. The scenario I have in mind is when there's a per-app default (the one you describe, always correct) and a per-user default overriding the latter. This is assuming #58 is implemented.
The per-user default is not supposed to be changed often, hence the user will save it in a "default config file". But something external can invalidate it. For instance, the user's data directory could get unmounted. In this case, ideally running `main.py --help` would show a reasonable error message. The current implementation does that (I believe), and ideally #58 would preserve it. Thanks again!

**Comment by mauvilsa** [comment]
This is now part of release v3.16.0.
