### ISSUE TITLE
Help messages for subparsers

### ISSUE THREAD

**Issue by stasbel** [omni-us/jsonargparse#61]
I want to print nice help message with sub parser added by key `parser` with following: `./program.py --parser.help`. Now, it's just an unrecognised argument for main parser.

**Comment by mauvilsa** [comment]
I don't understand what you want. Please improve the description including a code snippet, output of how it behaves now and what kind of output is it that you would like to see.

**Comment by stasbel** [comment]
```python3
from jsonargparse import ArgumentParser, ActionParser

inner_parser = ArgumentParser(prog='app1')
inner_parser.add_argument('--op1')

outer_parser = ArgumentParser(prog='app2')
outer_parser.add_argument('--inner', action=ActionParser(parser=inner_parser))

outer_parser.parse_args(['--inner.help'])
```

=>

```
Unrecognized arguments: --inner.help
```

**Comment by mauvilsa** [comment]
As per the request in https://github.com/omni-us/jsonargparse/issues/41 the options of inner parsers were moved to the main parser help. What you are requesting now is the old behavior. If someone wants to see the help they can use the main help. Having two ways of getting the same help is not a priority. Furthermore, the change done to support https://github.com/omni-us/jsonargparse/issues/41 makes it very hard to implement this.
