### ISSUE TITLE
Parsing to a list of dataclasses with nested dataclass fails

### ISSUE THREAD

**Issue by maticus** [omni-us/jsonargparse#614]
## 🐛 Bug report

Parsing a configuration to a list of dataclasses which contain nested dataclass fails.

### To reproduce

Run following code: 

```python
import jsonargparse
from dataclasses import dataclass

@dataclass
class B:
    # THIS WORKS
    # an_int: int = 7
    # THIS CAUSES AN ERROR
    an_int: int

@dataclass
class A:
    b: B

def fun(a: list[A]):
    print(a)

jsonargparse.CLI(fun)
```

Like so:
```
python python-jsonargparse-list-of-dataclasses.py '[{b: {an_int: 3}}]'
```

I'm seeing an error:
```
argparse.ArgumentError: Validation failed: Key "b.an_int" is required but not included in config object or its value is None.
```
Attaching full traceback.
[traceback.txt](https://github.com/user-attachments/files/17618428/traceback.txt)

### Expected behavior

We should see following printed to the stdout:
```
[A(b=B(an_int=3))]
```

### Environment

- jsonargparse version: 4.33.2
- Python version: 3.10.12
- How jsonargparse was installed: `pip install --user --update jsonargparse`
- OS: Ubuntu 22.04.4 LTS

**Comment by mauvilsa** [comment]
Thank you for reporting! I will look at it later.
