### ISSUE TITLE
Utility for instantiating class from `Namespace`?

### ISSUE THREAD

**Issue by EthanMarx** [omni-us/jsonargparse#620]
Is there a utility to instantiate a class from a namespace? 

```python

class MyClass:
    def __init__(self, arg: float):
        self.arg = arg
```

```python
namespace = Namespace(class_path = "path.to.MyClass', init_args=Namespace(arg=1.0))
obj = class_from_namespace(namespace)
assert isinstance(obj, MyClass) 
```

**Comment by mauvilsa** [comment]
That is what `ArgumentParser.instantiate_classes` is for. This has been asked before for `dict` instead of `Namespace` but the same applies. See https://github.com/omni-us/jsonargparse/issues/547#issuecomment-2223725228

**Comment by EthanMarx** [comment]
Thanks!
