### ISSUE TITLE
Adding configuration file changes parsed paths in a script

### ISSUE THREAD

**Issue by hadipash** [omni-us/jsonargparse#622]
The addition of configuration files changes the parsed path location relative to the configuration location rather than the working directory location.

### To reproduce

```python
from jsonargparse import ActionConfigFile, ArgumentParser
from jsonargparse.typing import Path_fc


def print_path(path: Path_fc):
    print(path.absolute)


if __name__ == "__main__":
    parser = ArgumentParser()
    parser.add_argument("-c", "--config", action=ActionConfigFile)
    parser.add_function_arguments(print_path)
    cfg = parser.parse_args()
    print_path(cfg.path)
```

### Expected behavior
Expected
```shell
python test_argparse.py --path=test.txt
```
and
```shell
python test_argparse.py --path=test.txt -c=config/config.yaml
```
to return the same output. However, the former returns `/home/admin/test/test.txt`, while the latter returns `/home/admin/test/config/test.txt`.

### Environment

- jsonargparse version: 4.33.2
- Python version: 3.9
- How jsonargparse was installed: pip install --upgrade jsonargparse[signatures,omegaconf,urls]

**Comment by mauvilsa** [comment]
@hadipash is it clear why the current behavior is the expected one?

**Comment by hadipash** [comment]
Thanks for your prompt reply. The current behavior is clear when I specify the path inside the config file. However, it's counterintuitive to me that when I pass the path to the Python script, it's relative to the config rather than the working directory.

**Comment by hadipash** [comment]
Sorry, my bad. The order of arguments matters. If I want to preserve the path relative to the working directory, I should specify it after the config: `python test_argparse.py -c=config/config.yaml --path=test.txt`. Thank you for your prompt reply!
