### ISSUE TITLE
Unclear error message when using wrong config file for argument group

### ISSUE THREAD

**Issue by Andry-Bal** [omni-us/jsonargparse#64]
### Setup to reproduce the issue:
```
from jsonargparse import ArgumentParser

class A:
    def __init__(self, param: int):
        ...

if __name__ == '__main__':
    parser = ArgumentParser()
    parser.add_class_arguments(A, nested_key='a')
    parser.parse_args()

```
Run parameters:
`--a ./non_existent_or_wrong_config.yaml`

### Expected behavior
Informative _File not exists_ message that makes it clear what went wrong (e.g. like when using _ActionConfigFile_)

### Current behavior
`error: vars() argument must have __dict__ attribute` which is quite confusing.

**Comment by mauvilsa** [comment]
Thank you for reporting. This might be a regression introduced in the latest release.

**Comment by mauvilsa** [comment]
This wasn't a regression. This is now fixed in master.
