### ISSUE TITLE
Support dot-notation with no dot for "class_path"

### ISSUE THREAD

**Issue by bryant1410** [omni-us/jsonargparse#65]
When creating objects using "class_path", it doesn't support creating built-in objects, that don't have a dot notation, such as `object`, `slice`, and `range`. It fails because it tries to split the path based on a dot and extract two strings out of it, but there's no dot.

I think it'd be good to support this type of objects.

**Comment by mauvilsa** [comment]
I think something like `builtins.range` works, no? Right now I would not allow `class_path` values without a dot. There is an upcoming feature that might depend on this.

From another perspective, the use of `class_path` is intended for type hints that work like subclasses. That is, a parameter can be an instance of that class or a subclass of it. Right now I can't think of a use case in which I would use a built-in as a type hint to accept subclasses of them. Maybe you can give an example in which this does make sense. For me `slice` and `range` would make more sense as registered types such that the value would use the range notation as in lists. 

What would be the point of giving `object` as the value for `class_path`? I guess this means that the type hint is `object`, what is this supposed to do?

**Comment by mauvilsa** [comment]
@bryant1410 any comments given what I wrote?

**Comment by bryant1410** [comment]
Oh, didn't think of `builtins` module.

Didn't know that `class_path` is only for subclasses.

> What would be the point of giving `object` as the value for `class_path`? I guess this means that the type hint is `object`, what is this supposed to do?

Would be kind of `Any`.

I understand now. I'm closing the issue. Thanks for the prompt reply and sorry for the delay!
