### ISSUE TITLE
Shouldn't signatures typehints support collections?

### ISSUE THREAD

**Issue by bryant1410** [omni-us/jsonargparse#69]
I have a subclass that takes an arg as input of type `Union[Iterable[MyClass], Mapping[str, MyClass]]` (`Union`, `Iterable`, and `Mapping` coming from `typing`).

I see it fails because it checks with `is_class_typehint`, and none of `Iterable` nor `Mapping` are "classes":

https://github.com/omni-us/jsonargparse/blob/e7ab0f3c2e687563a5f5e8eca8087f61b39977dd/jsonargparse/signatures.py#L329-L335

But shouldn't it support collections when checking the typehints? They seem to actually be supported when instantiating or calling the action (using `adapt_typehints`).

**Comment by mauvilsa** [comment]
What do you mean by collections? Also can you please post here a code snippet that can be used to reproduce the problem.

**Comment by bryant1410** [comment]
Such as the ones of the arg type: `Iterable`, `Mapping`, but also lists, tuples, etc. Or the ones in [`collections`](https://docs.python.org/3/library/collections.abc.html) more broadly.

I can try to create a small example as the code I have now is more complicated. But it's essentially about what I described there: I use `add_subclass_arguments`, then I try to parse a subclass that takes as arg in `__init__` a type like `Union[Iterable[MyClass], Mapping[str, MyClass]]`, and it fails because there's no type available for this arg.

**Comment by bryant1410** [comment]
I managed to reproduce it with a small example.

`a.py`:

```python
from typing import Iterable, Mapping, Union

import jsonargparse
from jsonargparse import ActionConfigFile


class C:
    def __init__(self, size: int) -> None:
        self.size = size


class A:
    pass


class B(A):
    def __init__(self, b: Union[Iterable[C], Mapping[str, C]]) -> None:
        self.b = b


if __name__ == '__main__':
    import a  # Otherwise it'd say that `a.B` is not a subclass of `__main__.A`. It is of `a.A`.
    # See https://stackoverflow.com/a/38477315/1165181
    parser = jsonargparse.ArgumentParser()
    parser.add_argument("--config", action=ActionConfigFile)
    parser.add_subclass_arguments(a.A, nested_key="a", required=True)

    args = parser.parse_args(["--config", "a.yml"])
```

`a.yml`:

```yml
a:
  class_path: a.B
  init_args:
    b:
      - class_path: a.C
        init_args:
          size: 2
      - class_path: a.C
        init_args:
          size: 4
```

But it fails for a reason different from the one I mentioned. It fails because `Mapping` isn't a "root type" when checked in `ActionTypeHint.is_supported_typehint`. I'm gonna send a patch for it soon.

In addition, maybe Union should work as an OR there instead of an AND? Maybe this should be fixed as well. Because there may be some type in the union that it's unsupported and makes the whole parsing fail while that specific type may not be used.

**Comment by mauvilsa** [comment]
> In addition, maybe Union should work as an OR there instead of an AND? Maybe this should be fixed as well. Because there may be some type in the union that it's unsupported and makes the whole parsing fail while that specific type may not be used.

It doesn't work like an AND. If you look at [typehints.py#L347](https://github.com/omni-us/jsonargparse/blob/e7ab0f3c2e687563a5f5e8eca8087f61b39977dd/jsonargparse/typehints.py#L347) the only case in which an exception is raised is when the value is invalid for all types in the union.

**Comment by mauvilsa** [comment]
> Such as the ones of the arg type: `Iterable`, `Mapping`, but also lists, tuples, etc. Or the ones in [`collections`](https://docs.python.org/3/library/collections.abc.html) more broadly.

Certainly all types from the standard library that makes sense to become configurable should be supported. Great that you are adding missing ones. Please change the title to me more specific.
