### ISSUE TITLE
Default arguments with default_config_files

### ISSUE THREAD

**Issue by Solvik** [omni-us/jsonargparse#7]
I've stumbled upon an issue using default arguments and default_config_files

Here's the config
```
# cat /root/config.yaml
a: b
```

The code
```
import jsonargparse

p = jsonargparse.ArgumentParser(
    default_config_files=[
        '/root/config.yaml'
    ],
    prog='test',
)

p.add_argument('-c', '--config', action=jsonargparse.ActionConfigFile)
p.add_argument('-a', default='c')
print(p.parse_args())
```

And its execution
```
# python3 test.py 
namespace(__cwd__=['/root'], a='c', config=None)
# python3 test.py -c /root/config.yaml
namespace(__cwd__=['/root'], __path__=Path(path="/root/config.yaml", abs_path="/root/config.yaml", cwd="/root"), a='b', config=[Path(path="/root/config.yaml", abs_path="/root/config.yaml", cwd="/root")])

```

**Comment by mauvilsa** [comment]
@Solvik thank you very much for reporting. This is my fault. I have been working on ActionParser which for which I made a big change in parse_args which introduced this regression, but there was no unit test to check the precedence of the different sources, so I didn't notice.

I have added a unit test to check the precedence and fixed the issue. Please check.

**Comment by Solvik** [comment]
The issue is fixed, thanks :)
