### ISSUE TITLE
Support optional comment header for printed configs

### ISSUE THREAD

**Issue by carmocca** [omni-us/jsonargparse#79]
## Pitch

Allow passing a function that returns an `str` so the config generated with `--print_config` has a comment header with that string.

This would be useful to save which version was used to generate a config inside the config itself.

```console
$ python script.py --print_config
# a comment
# which might span
# multiple lines
# and is configurable
foo: 1
```

**Comment by mauvilsa** [comment]
Can you please explain more. Is the comment header one for the whole printed yaml? Why a function and based on what the string that returns changes?

Note that comments coming from docstrings are already included by using `--print_config=comments`. If an additional feature related to comments is added it would only be enabled by giving this option.

**Comment by carmocca** [comment]
The idea is to be able to add some metadata to the config file for reproducibility. For Lightning, it could include the version when the config file was generated:

```python
# Lightning version: v1.4.1
trainer:
  ...
model:
  ...
````

> Is the comment header one for the whole printed yaml?

Yes

> Why a function and based on what the string that returns changes?

Actually this is not a hard requirement so passing the string directly is okay

> Note that comments coming from docstrings are already included by using --print_config=comments. If an additional feature related to comments is added it would only be enabled by giving this option.

This would be okay as long as

- A `--print_config=header` is implemented, which would only include the header this PR requests. `comments` could include header + comments 
- A default `print_config` value can be programatically set for the `ArgumentParser`. This way `--print_config` can default to `--print_config=header`

Although you could also expect that if this metadata/header is passed to the parser, it should be included in the config by default

**Comment by mauvilsa** [comment]
This has been implemented in commit https://github.com/omni-us/jsonargparse/commit/00f42e0d0127b082843acf03c7919e91f24ddf39. Based on the described use case it didn't make sense to have a switch in `--print_config` so it is only a property of the parser.
