### ISSUE TITLE
Both environment variables and config file does not work

### ISSUE THREAD

**Issue by didirus** [omni-us/jsonargparse#8]
A variable in my config.yaml file is not parsed when having `default_env=True`: 

I define my parser:
```parser = ArgumentParser(env_prefix='CV', default_env=True, version=__version__)```

and add the config file action to the argument:

```parser.add_argument('--config', action=ActionConfigFile, help='Path to a yaml configuration file.')```

And then my required argument is not set, even though it's present in the config file:
```jsonargparse.ParserError: Config checking failed :: Key "outputpath" is required but its value is None.```

**Comment by mauvilsa** [comment]
@didirus I have created a python script and config file trying to reproduce your problem. I attach them here [issue_8.zip](https://github.com/omni-us/jsonargparse/files/4174084/issue_8.zip). Unfortunately I can't reproduce. Please check the example to see if this does reflect your situation and also please check again with your code and the latest jsonargparse version 2.23.2 which might have already resolved this.

**Comment by didirus** [comment]
@mauvilsa, I can reproduce it in your example, by setting out to required=True.

**Comment by mauvilsa** [comment]
@didirus this should be fixed now. Please try it out with the new version 2.23.3.
