### ISSUE TITLE
No error message when using ArgumentParser.instantiate_classes()

### ISSUE THREAD

**Issue by yunxie12** [omni-us/jsonargparse#81]
Hello, I found some odd codes at https://github.com/omni-us/jsonargparse/blob/57741c20c488ff4126018a4b721bd758f6d271c0/jsonargparse/core.py#L1111.
I am confused why KeyError should be ignored. When instantiating a class, KeyError is common, for example, try to get a value from a dict using a nonexistent key. It takes me lots of time to debug my code with KeyError.
Anyway, jsonargparse is a great package and help me a lot.
I wish we can discuss my confusion.

**Comment by mauvilsa** [comment]
I think you are right, that is a mistake. The try should only wrap the `_get_key_value` line and only if no exception the rest would be executed. Would you like to create a pull request with the fix?

**Comment by mauvilsa** [comment]
Since there was no response I went ahead and fixed it. Currently in master and will be part of the next release. @yunxie12 please try again with jsonargparse from master your code in which the instantiation gave KeyError to verify that the fix worked.

**Comment by yunxie12** [comment]
The fix works. Thanks you!
