### ISSUE TITLE
support saving to remote filesystem

### ISSUE THREAD

**Issue by awaelchli** [omni-us/jsonargparse#86]
jsonargparse can read config files from S3 already. 
We think a reasonable addition would be to also let the ArgumentParser save to a remote filesystem. 
The feature would require us to extend the [save() function](https://github.com/omni-us/jsonargparse/blob/df466645f64a4fdd5983197ca6fe28ca38126d04/jsonargparse/core.py#L853) with a call to fsspec. 

Related issue in Lightning: https://github.com/PyTorchLightning/pytorch-lightning/issues/8843

**Comment by mauvilsa** [comment]
This is now supported in the current version in master. Later I will create a pull request in pytorch-lightning for a small change related to this.

**Comment by awaelchli** [comment]
that was fast!
