### ISSUE TITLE
Parsing of dict is failing in v3.18.0

### ISSUE THREAD

**Issue by Andry-Bal** [omni-us/jsonargparse#87]
### Code to reproduce the issue:
```python
from typing import Dict
from jsonargparse import ArgumentParser, ActionConfigFile


class Foo:
    def __init__(self, d: Dict[int, str]):
        pass


cfg = """
d:
    1: val1
    2: val2
"""


def main():
    parser = ArgumentParser()
    parser.add_class_arguments(Foo)
    parser.add_argument('--config', action=ActionConfigFile)
    parser.parse_args(['--config', cfg])


if __name__ == '__main__':
    main()
```
### Current behavior:
Exits with:
`error: keywords must be strings`

**Comment by mauvilsa** [comment]
From the title do you mean that this worked on previous versions but now is failing in v3.18.0? If it did work before could you please say in which jsonargparse and python version.

**Comment by Andry-Bal** [comment]
Yes, it worked with **Python 3.9.5** and **jsonargparse 3.17.0**.

**Comment by Andry-Bal** [comment]
Same thing with **Python 3.9.6** and **jsonargparse 3.19.0**.

**Comment by mauvilsa** [comment]
Yes, I know. I modified the code above so that the same problem is reproduced in earlier versions of python.

**Comment by mauvilsa** [comment]
Currently I am refactoring a core part of jsonargparse which has been the main cause of many issues including this one. Thus it will take a bit to get this fixed.

**Comment by mauvilsa** [comment]
The fix is now in the master branch. As said this will be part of the next major release.
