### ISSUE TITLE
Empty / Null argument in config file should fallback to default value

### ISSUE THREAD

**Issue by idobrusin** [omni-us/jsonargparse#9]
I have a use-case where I want to populate from a config file, with empty values for some parameters. These parameters have a type but have `None` as default, so i want to be able to keep them in the config with their default value (which is empty/None).

### Example
```
$ cat config.yaml
a:
```

```python
import jsonargparse as argparse

if __name__ == '__main__':
    parser = argparse.ArgumentParser()
    parser.add_argument('--config', action=argparse.ActionConfigFile)
    parser.add_argument('--a', type=int, default=None)
    print(parser.parse_args())
```

```
$ python3 test.py --config config.yaml
[...]
jsonargparse.ParserError: Parser key "a": int() argument must be a string, a bytes-like object or a number, not 'NoneType'
```

I would expect the parser to skip empty values and use the default value. So for parameters which explicitly allow `None` values it should be possible to pass it.  

### Question
Should jsonargparse allow empty values for typed parameters and use the default value instead of throwing a parsing error? 
Or is there already a way to achieve this with some options in jsonargparse?

Edit: I just tested this with `type=str`, where this doesn't occur, so this issue seems to be limited to int (and similar types).
Edit2: With `type=str` the parameter will have the value `"None"` as a string, so this applies to string also. See solution below to handle this case.

**Comment by mauvilsa** [comment]
Just define your own custom type. That is
```python
def int_or_none(x):
    return x if x is None else int(x)
parser.add_argument('--a', type=int_or_none, default=None)
```

**Comment by idobrusin** [comment]
Thanks for the quick reply :) 
I extended your solution to be more generic, allowing to wrap a type with `NoneableType` which will return the correct type or `None`.

```python
class NoneableType(object):
    def __init__(self, type):
        self._type = type

    def __call__(self, value):
        if value is not None:
            return self._type(value)
        return value

parser.add_argument('--a', type=NoneableType(int), default=None)
```
