### ISSUE TITLE
Support `--print_config skip_default`

### ISSUE THREAD

**Issue by carmocca** [omni-us/jsonargparse#91]
Add support for `--print_config skip_default` so only the values different to the default are printed.

Two main benefits:
- Removes the manual work of removing the extra arguments from a config. However, this isn't recommended for reproducibility as it's useful to know exactly what was set.
- Improves backward compatibility. Often features are deprecated in a way that the default argument for a function is re-routed to the new implementation. Since the config saves all old defaults and passes them to the program, it is likely the program will fail when support for the old value is removed.

**Comment by mauvilsa** [comment]
An initial version of this is implemented in pull request https://github.com/omni-us/jsonargparse/pull/132. @carmocca can you please test this hopefully with some real use case.
