### ISSUE TITLE
`self.logger` undefined on `SignatureArguments`.

### ISSUE THREAD

**Issue by ramonemiliani93** [omni-us/jsonargparse#92]
Hi I have been trying to skip an argument on a `LightningCLI` from `pytorch_lightning` but it is unable to log the skipped parameter and therefore fails. I also glimpsed through the class but couldn't find the definition for the logger.

```python
import dataclasses

import pytorch_lightning as pl
from pytorch_lightning.utilities.cli import LightningCLI


@dataclasses.dataclass
class Foo:
    bar: int
    skip: int


class ErrorCLI(LightningCLI):

    def add_arguments_to_parser(self, parser):
        group = parser.add_argument_group("group")
        group.add_class_arguments(Foo, skip={"skip"})


if __name__ == "__main__":
    cli = ErrorCLI(pl.LightningModule)
```

If you save the snippet as `trainer.py` and run  `python trainer.py fit --print_config > default.yaml` it will fail in `signatures.py` when logging the skipped parameter:
```
AttributeError: '_ArgumentGroup' object has no attribute 'logger'
```
 If the group is removed then it stops failing. If this should be moved to pytorch lightning let me know!

**Comment by mauvilsa** [comment]
Thanks for reporting. Will look at it.

**Comment by mauvilsa** [comment]
Fixed. Will be included in the next patch or minor release.
