### ISSUE TITLE
`classmethod` first parameter skipped.

### ISSUE THREAD

**Issue by ramonemiliani93** [omni-us/jsonargparse#93]
Hi, when doing the following I get a parameter missing:

```python
import dataclasses

from jsonargparse import CLI


@dataclasses.dataclass
class Foo:
    @classmethod
    def bar(cls, a: int, b: int, c: int):
        return a + b + c


if __name__ == "__main__":
    cli = CLI()
    cli.add_method_arguments(Foo, "bar", as_group=False)
```

When running the file as `python main.py bar --help` only `b` and `c` are parsed. Seems the problem is in `_add_signature_arguments` of `signatures.py`. On the following loop:

```python
for num, param in enumerate(inspect.signature(func).parameters.values()):
    if skip_first and num == 0:
        continue
```
For a `classmethod` the `inspect.signature` will not return the `cls` param and since `skip_first` is set to `True` the first parameter is skipped.

**Comment by mauvilsa** [comment]
Thank you for reporting! The issue is that `add_method_arguments` was only designed for normal class methods, not for `classmethod` or `staticmethod`. Certainly `add_method_arguments` can be improved ideally to support any kind of method and/or raise exceptions when it is used in a unexpected way.

**Comment by ramonemiliani93** [comment]
Thanks for the reply @mauvilsa! It seems very useful to support `classmethod` since some classes have protected constructors hence the `add_class_arguments` wont work. Are you accepting PRs? I could help with this.

**Comment by mauvilsa** [comment]
> Are you accepting PRs? I could help with this.

Sure.

As a workaround maybe using `add_function_arguments` works for `classmethod`. Still it would be better if `add_method_arguments` supports the three method types.

**Comment by ramonemiliani93** [comment]
Works like charm! Thanks 🙌
