### ISSUE TITLE
Consider parameters of type POSITIONAL_OR_KEYWORD as KEYWORD if only **kwargs present

### ISSUE THREAD

**Issue by florianblume** [omni-us/jsonargparse#98]
When not providing default values for any method or function argument, i.e. having only `POSITIONAL_OR_KEYWORD` arguments, the parameters should be considered `KEYWORD` in case that the method or function signature only has `**kwargs` and not `*args`. (Taken from our Slack discussion).

**Comment by mauvilsa** [comment]
With the current version in master it should now be working like this.
